/* 자동 생성 — 필터링 제외 목록 / 2026-05-03 14:50:20 KST */
var EXCLUDED_DATA = {
  "updated_at": "2026-05-03 14:50:20 KST",
  "total": 241,
  "jobs": [
    {
      "title": "성수역 소재 퍼포먼스 마케팅대행사 퍼포먼스 마케팅 AE",
      "company": "파워에이치알",
      "location": "서울 성동구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력3년 대졸(2~3년)",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=2605030000035&infoTypeCd=CIN&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 퍼포먼스 마케팅"
    },
    {
      "title": "서울숲역 소재  광고대행사 퍼포먼스 마케팅 담당(사원~대리급)",
      "company": "파워에이치알",
      "location": "서울 성동구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력1년 대졸(2~3년)",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=2605030000036&infoTypeCd=CIN&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 퍼포먼스 마케팅"
    },
    {
      "title": "병원마케팅 전문 퍼포먼스 마케팅 담당",
      "company": "파워에이치알",
      "location": "서울 성동구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력1년 대졸(2~3년)",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=2605030000037&infoTypeCd=CIN&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 퍼포먼스 마케팅"
    },
    {
      "title": "게임 기획자 및 서비스 기획자 모집",
      "company": "토리에듀핀",
      "location": "서울 마포구  등",
      "deadline": "2026-06-02",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "신입/경력2년 대졸(4년)",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=2605030000162&infoTypeCd=CIN&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 서비스 기획자"
    },
    {
      "title": "[주5일 /초봉3000] (숏폼) 광고 컨텐츠/영상PD 경력직 모집",
      "company": "동탄휴대폰성지 도매폰센타",
      "location": "경기 화성시",
      "deadline": "2026-06-01",
      "type": "",
      "salary": "연봉 3,000 만원 ~ 4,000 만원",
      "description": "신입/경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=50812230&infoTypeCd=CJK&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 숏폼"
    },
    {
      "title": "NEW 디지털광고 퍼포먼스 마케터 경력사원 채용 공고",
      "company": "주식회사 디지털히어로",
      "location": "대구 달서구",
      "deadline": "2026-05-31",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력1년 대졸(2~3년)",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=53782057&infoTypeCd=CSI&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 퍼포먼스 마케터"
    },
    {
      "title": "[병역특례 지원 가능 ]AI 개발자(VLM +CNN)",
      "company": "(주)원모어시큐리티",
      "location": "세종",
      "deadline": "2026-06-01",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력무관 석사",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=53782734&infoTypeCd=CSI&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "[신입] 대전 홍보대행사 온라인 및 SNS 홍보, 유튜브 운영 신입",
      "company": "(주)제이레퍼토리",
      "location": "대전 중구",
      "deadline": "2026-07-01",
      "type": "",
      "salary": "연봉 2,600 만원 ~ 2,600 만원",
      "description": "신입 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=53782894&infoTypeCd=CSI&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 유튜브 운영"
    },
    {
      "title": "백엔드 개발자 채용 - 미국 보디빌딩 보충제 직구 머슬코리아",
      "company": "머슬코리아(MuscleKorea)",
      "location": "서울 강남구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력1년 대졸(4년)",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=53782900&infoTypeCd=CSI&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "커피빈 8H 슈퍼바이저 채용 (인천공항 지역)",
      "company": "(주)커피빈코리아",
      "location": "인천   등",
      "deadline": "2026-06-01",
      "type": "",
      "salary": "월급 240 만원 ~ 240 만원",
      "description": "경력무관 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=53783493&infoTypeCd=CSI&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "업체명: 커피빈"
    },
    {
      "title": "플랫폼 UI/UX 디자이너 인턴 채용",
      "company": "(주)토리에듀핀",
      "location": "전북 전주시 덕진구 등",
      "deadline": "2026-06-01",
      "type": "",
      "salary": "월급 230 만원 ~ 230 만원",
      "description": "경력무관 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=53783577&infoTypeCd=CSI&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: ui/ux 디자이너"
    },
    {
      "title": "교육 플랫폼 java 경력 개발자 모십니다",
      "company": "(주)공간과가치",
      "location": "서울 서초구",
      "deadline": "2026-05-31",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력3년 고졸",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=53557373&infoTypeCd=CSI&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "[MUSMA] 회로(FW)개발자 경력직 채용공고(부산근무)",
      "company": "(주)무스마",
      "location": "부산   등",
      "deadline": "2026-05-11",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력3년 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=53749953&infoTypeCd=CSI&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "[다우키움계열사 ㈜와이즈버즈] 퍼포먼스 마케터(경력 2년 이상)",
      "company": "㈜와이즈버즈",
      "location": "경기 성남시 수정구 등",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력2년 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=50819926&infoTypeCd=CJK&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 퍼포먼스 마케터"
    },
    {
      "title": "[상암/평일오전] iMBC 뉴스 영상 편집 사원 모집(5/6 마감)",
      "company": "㈜엠플라인",
      "location": "서울 마포구",
      "deadline": "2026-06-29",
      "type": "",
      "salary": "월급 237 만원 ~ 237 만원",
      "description": "신입/경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=50821928&infoTypeCd=CJK&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 영상 편집"
    },
    {
      "title": "[무신사스탠다드] 홍대점 플로어 매니저 채용",
      "company": "(주)무신사리테일서비스(MUSINSA RETAIL SERVICES)",
      "location": "서울 마포구",
      "deadline": "2026-05-31",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력1년 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=50822683&infoTypeCd=CJK&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "업체명: 무신사"
    },
    {
      "title": "[무신사스탠다드] 강남점 플로어 매니저 채용",
      "company": "(주)무신사리테일서비스",
      "location": "서울 서초구",
      "deadline": "2026-05-31",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력1년 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=53776409&infoTypeCd=CSI&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "업체명: 무신사"
    },
    {
      "title": "글로벌 패션 커머스 Node.js 백엔드 개발자 (병역특례 가능)",
      "company": "페칭",
      "location": "서울 성동구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=139191&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "글로벌 패션 커머스 주니어 Node.js 백엔드 개발자 (병역특례 ...",
      "company": "페칭",
      "location": "서울 성동구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력무관 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=234680&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "[WIPPY] 퍼포먼스 마케터",
      "company": "엔라이즈(NRISE)",
      "location": "서울 강남구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=226814&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 퍼포먼스 마케터"
    },
    {
      "title": "글로벌 패션 커머스 UI/UX 디자이너",
      "company": "페칭",
      "location": "서울 성동구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=257235&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: ui/ux 디자이너"
    },
    {
      "title": "글로벌 패션 커머스 프론트엔드 개발자 (병역특례 가능)",
      "company": "페칭",
      "location": "서울 성동구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=248170&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "글로벌 패션 커머스 프론트엔드 개발자 주니어 (병역 특례 가능)",
      "company": "페칭",
      "location": "서울 성동구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력무관 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=301316&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "[미리디] 시니어 데이터 분석가 (Senior Data Analys...",
      "company": "미리디",
      "location": "지역무관",
      "deadline": "2026-05-08",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=328205&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 데이터 분석가"
    },
    {
      "title": "[미리캔버스] 시니어 프론트엔드 개발자",
      "company": "미리디",
      "location": "지역무관",
      "deadline": "2026-05-22",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=337323&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "풀스텍 개발자 (5년 이상)",
      "company": "어반데이터랩",
      "location": "서울 강남구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=334214&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "[미리캔버스] 백엔드 개발자",
      "company": "미리디",
      "location": "지역무관",
      "deadline": "2026-05-22",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=337958&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "글로벌 B2B PM",
      "company": "씨제이올리브영(CJ올리브영)",
      "location": "서울 용산구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=345803&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "[feura] 그로스 마케터 (Growth Marketing)",
      "company": "에고이즘",
      "location": "서울 성동구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=347222&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 그로스 마케터"
    },
    {
      "title": "[병역특례] 미리캔버스 에디터 엔지니어 [전문연구요원]",
      "company": "미리디",
      "location": "지역무관",
      "deadline": "2026-05-29",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=347499&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 병역특례"
    },
    {
      "title": "[미리캔버스] Senior DevOps Engineer",
      "company": "미리디",
      "location": "지역무관",
      "deadline": "2026-05-15",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=349603&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: devops"
    },
    {
      "title": "MLOps 엔지니어",
      "company": "온택트헬스",
      "location": "지역무관",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=350626&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: mlops"
    },
    {
      "title": "데이터 엔지니어",
      "company": "111퍼센트",
      "location": "서울 성동구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=351332&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 데이터 엔지니어"
    },
    {
      "title": "[Deepflow] 데이터 엔지니어 (Data Engineer)",
      "company": "임팩티브에이아이",
      "location": "서울 강남구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=351971&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 데이터 엔지니어"
    },
    {
      "title": "Senior MLOps 엔지니어",
      "company": "온택트헬스",
      "location": "지역무관",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=354270&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: mlops"
    },
    {
      "title": "풀스택 개발자 (5년+)",
      "company": "네오플랫",
      "location": "서울 마포구",
      "deadline": "2026-05-31",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=354917&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "쿠팡페이 백엔드 팀장 (Engineering Manager)",
      "company": "쿠팡",
      "location": "서울 송파구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=356657&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 백엔드"
    },
    {
      "title": "AI 서비스 기획자 (PM/PO)",
      "company": "아티언스",
      "location": "서울 마포구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=357649&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 서비스 기획자"
    },
    {
      "title": "백엔드 개발자(RDPLINE) 3년 이상",
      "company": "비큐에이아이",
      "location": "지역무관",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=358780&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "백엔드개발자(WIGOVIEW) 3년 이상",
      "company": "비큐에이아이",
      "location": "지역무관",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=358779&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "AI개발자 10년 이상",
      "company": "비큐에이아이",
      "location": "지역무관",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=358788&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "서비스 기획자 3년 이상",
      "company": "비큐에이아이",
      "location": "지역무관",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=358783&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 서비스 기획자"
    },
    {
      "title": "백엔드 엔지니어 3년 이상",
      "company": "에타일렉트로닉스",
      "location": "서울 용산구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=358791&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 백엔드"
    },
    {
      "title": "프론트엔드 엔지니어 3년 이상",
      "company": "에타일렉트로닉스",
      "location": "서울 용산구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=358802&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 프론트엔드"
    },
    {
      "title": "시스템 엔지니어(DevOps)",
      "company": "매드엔진",
      "location": "경기 성남시",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=358833&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: devops"
    },
    {
      "title": "콘텐츠 퍼포먼스 마케터",
      "company": "트리플오스",
      "location": "경기 성남시",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=358843&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 퍼포먼스 마케터"
    },
    {
      "title": "프론트엔드 엔지니어 (5년 이상)",
      "company": "마이프랜차이즈",
      "location": "지역무관",
      "deadline": "2026-05-11",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=358859&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 프론트엔드"
    },
    {
      "title": "웨어러블 로봇 전장 하드웨어 개발자 (펌웨어 가능자 우대)",
      "company": "리보디스",
      "location": "서울 관악구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=358858&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "백엔드 웹프로그래머 (Spring, MSA) (7년 이상)",
      "company": "키트웍스",
      "location": "지역무관",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=358872&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 백엔드"
    },
    {
      "title": "백엔드 웹프로그래머 (Spring, MSA) (2~4년)",
      "company": "키트웍스",
      "location": "지역무관",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=358874&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 백엔드"
    },
    {
      "title": "백엔드 웹프로그래머 (Spring, MSA) (4~6년)",
      "company": "키트웍스",
      "location": "지역무관",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=358873&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 백엔드"
    },
    {
      "title": "[인턴] 영화 숏폼 제작 PD",
      "company": "키노라이츠",
      "location": "서울 강남구",
      "deadline": "2026-05-11",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력무관 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=358923&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 숏폼"
    },
    {
      "title": "[리텐틱스] 데이터 사이언티스트 (Data Scientist) 3년...",
      "company": "프라이데이즈랩(Retentics)",
      "location": "서울 강남구",
      "deadline": "2026-05-30",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=358944&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 데이터 사이언티스트"
    },
    {
      "title": "[바니스뉴욕] Beauty/Wellness 그래픽 디자이너 (3~5...",
      "company": "글로엔트그룹",
      "location": "서울 강남구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=358955&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 그래픽 디자이너"
    },
    {
      "title": "DevOps Engineer",
      "company": "에스티씨랩(STCLab)",
      "location": "서울 강남구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=358977&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: devops"
    },
    {
      "title": "백엔드 엔지니어 (Infra & Database Specialist...",
      "company": "그로잉세일즈",
      "location": "서울 마포구",
      "deadline": "2026-05-08",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=358982&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 백엔드"
    },
    {
      "title": "고정밀 실시간 데이터 시각화 AR 개발자(계약직)",
      "company": "알엑스",
      "location": "서울 마포구",
      "deadline": "2026-05-31",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=358986&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "DevOps Engineer",
      "company": "아임웹",
      "location": "서울 강남구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=358995&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: devops"
    },
    {
      "title": "앱 프로덕트 디자이너(계약직)",
      "company": "지나인",
      "location": "서울 마포구",
      "deadline": "2026-05-17",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=358996&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 프로덕트 디자이너"
    },
    {
      "title": "브랜드 영상 PD",
      "company": "왈로우",
      "location": "경기 하남시",
      "deadline": "2026-05-31",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=359042&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 영상 pd"
    },
    {
      "title": "상품제품 기획개발자(소형가전, 차량/캠핑용품)",
      "company": "왈로우",
      "location": "경기 하남시",
      "deadline": "2026-05-31",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=359051&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "브랜드 영상 PD",
      "company": "워로브라더스",
      "location": "경기 하남시",
      "deadline": "2026-05-31",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=359064&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 영상 pd"
    },
    {
      "title": "인플루언서 마케팅/커머스 매니저",
      "company": "왈로우",
      "location": "경기 하남시",
      "deadline": "2026-05-31",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=359060&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 인플루언서"
    },
    {
      "title": "웹 프로덕트 디자이너(계약직/육아휴직대체)",
      "company": "지나인",
      "location": "서울 마포구",
      "deadline": "2026-05-17",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=359062&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 프로덕트 디자이너"
    },
    {
      "title": "상품제품 기획개발자(소형가전, 차량/캠핑용품)",
      "company": "워로브라더스",
      "location": "경기 하남시",
      "deadline": "2026-05-31",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=359073&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "인플루언서 마케팅/커머스 매니저",
      "company": "워로브라더스",
      "location": "경기 하남시",
      "deadline": "2026-05-31",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=359077&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 인플루언서"
    },
    {
      "title": "프로덕트 매니저 / 플랫폼",
      "company": "파지티브호텔",
      "location": "서울 강남구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=359086&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 프로덕트 매니저"
    },
    {
      "title": "그래픽 디자이너",
      "company": "파지티브호텔",
      "location": "서울 강남구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=359099&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 그래픽 디자이너"
    },
    {
      "title": "퍼포먼스 마케터(5년 이하)",
      "company": "고이장례연구소",
      "location": "서울 관악구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=359109&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 퍼포먼스 마케터"
    },
    {
      "title": "[패션 스타트업] AI 프로덕트 디자이너",
      "company": "차일디",
      "location": "지역무관",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=359117&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 프로덕트 디자이너"
    },
    {
      "title": "북미(아마존, 틱톡샵) 퍼포먼스 마케팅",
      "company": "토리든",
      "location": "서울 송파구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=359162&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 퍼포먼스 마케팅"
    },
    {
      "title": "동남아(틱톡샵, 쇼피) 퍼포먼스 마케팅",
      "company": "토리든",
      "location": "서울 송파구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=359159&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 퍼포먼스 마케팅"
    },
    {
      "title": "소프트웨어 엔지니어",
      "company": "히포크랏 랩스(Hippocrat Labs)",
      "location": "서울 강남구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=359171&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 소프트웨어 엔지니어"
    },
    {
      "title": "그래픽 디자이너(BX)",
      "company": "파이브스페이스",
      "location": "서울 성동구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=359195&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 그래픽 디자이너"
    },
    {
      "title": "Python 백엔드 개발자 모집 (잠실 상주, 고급/특급)",
      "company": "단감소프트",
      "location": "지역무관",
      "deadline": "2026-05-05",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=358829&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "롯데리아 부개역점에서 매니저를 구합니다.",
      "company": "롯데리아인천부개역점",
      "location": "경기 부천시  등",
      "deadline": "2026-05-31",
      "type": "",
      "salary": "월급 300 만원 ~ 300 만원",
      "description": "경력1년 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=53779496&infoTypeCd=CSI&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "올리브영 상현역점 목금토 마감 CREW 구인",
      "company": "씨제이올리브영 주식회사",
      "location": "경기 용인시 수지구",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116245411",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "컴포즈커피 안양is비즈타워점에서 함께 일할분 구합니다",
      "company": "컴포즈커피 안양IS비즈타워점",
      "location": "경기 안양시 동안구",
      "deadline": "2026-05-20",
      "type": "시간제",
      "salary": "시급 10,320원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116292062",
      "source": "알바몬",
      "_exclude_reason": "업체명: 컴포즈"
    },
    {
      "title": "올리브영 서울역점 주말 오픈 CREW 구인",
      "company": "올리브영 서울역점",
      "location": "서울 금천구",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116096436",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "올리브영 응암점 주말 마감 CREW 구인",
      "company": "씨제이올리브영 주식회사",
      "location": "서울 은평구",
      "deadline": "2026-05-09",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116341552",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "올리브영 인천인스파이어점 CREW 구인(교통비6,000원지원)",
      "company": "올리브영 인천인스파이어점",
      "location": "인천 서구 청라동",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116191056",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "컴포즈커피 압구정스마일점 오후직원 구합니다!!!",
      "company": "컴포즈커피 압구정스마일점",
      "location": "서울 강남구 신사동",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "월급 2,500,000원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116292060",
      "source": "알바몬",
      "_exclude_reason": "업체명: 컴포즈"
    },
    {
      "title": "[강남/컴포즈수서역점] 평일 미들타임 알바 모집",
      "company": "컴포즈커피 수서역점",
      "location": "서울 전체",
      "deadline": "2026-05-10",
      "type": "시간제",
      "salary": "시급 10,500원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116228028",
      "source": "알바몬",
      "_exclude_reason": "업체명: 컴포즈"
    },
    {
      "title": "[직영) 투썸플레이스 노원구청점]키친오픈,저녁스탭채용",
      "company": "투썸플레이스 노원구청점",
      "location": "서울 노원구 월계동",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,400원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116201563",
      "source": "알바몬",
      "_exclude_reason": "업체명: 투썸플레이스"
    },
    {
      "title": "[컴포즈커피] 평일 오픈 8:00~12:00 구합니다(월화수)",
      "company": "컴포즈커피 오산대역점",
      "location": "경기 오산시",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 11,000원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116252972",
      "source": "알바몬",
      "_exclude_reason": "업체명: 컴포즈"
    },
    {
      "title": "올리브영 현대시티아울렛동대문점 수목금 마감 CREW 구인",
      "company": "올리브영 현대시티아울렛동대문점",
      "location": "서울 중구",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116243433",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "CJ올리브영 수원금곡점 금토일 단기 CREW 구인",
      "company": "씨제이올리브영 주식회사",
      "location": "경기 수원시 권선구 금곡동",
      "deadline": "2026-05-23",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116343968",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "CJ올리브영 홍대사거리점 주말 마감 CREW 구인(요일 협의 가능)",
      "company": "씨제이올리브영 주식회사",
      "location": "서울 강서구",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116201560",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "CJ올리브영 홍대놀이터점 마감 CREW 구인",
      "company": "씨제이올리브영 주식회사",
      "location": "서울 마포구",
      "deadline": "2026-05-16",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116214086",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "투썸 파이낸셜뉴스빌딩점[직영점] 미들 스텝 모집",
      "company": "투썸플레이스 파이낸셜뉴스빌딩점",
      "location": "서울 서초구",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,400원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116191053",
      "source": "알바몬",
      "_exclude_reason": "업체명: 투썸플레이스"
    },
    {
      "title": "[급구]올리브영 신사서초점 수금토 오픈 Crew 구인(협의가능)",
      "company": "씨제이올리브영 주식회사",
      "location": "서울 전체",
      "deadline": "2026-05-15",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116343966",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "노브랜드버거 인천구월점 (모래내시장) 평일5일 마감 크루 모집",
      "company": "노브랜드버거 인천구월점",
      "location": "인천 남동구 구월동",
      "deadline": "2026-05-04",
      "type": "시간제",
      "salary": "시급 10,350원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116321034",
      "source": "알바몬",
      "_exclude_reason": "업체명: 노브랜드버거"
    },
    {
      "title": "올리브영 홍대입구역점 월금토일 오픈 CREW 구인(시간대 협의 가능)",
      "company": "씨제이올리브영 주식회사",
      "location": "경기 고양시 일산동구",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116166702",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "카페/경력자/성실/컴포즈커피 부천춘의점 평일 마감 구합니다",
      "company": "컴포즈커피 부천춘의점",
      "location": "경기 부천시 춘의동",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,320원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116186876",
      "source": "알바몬",
      "_exclude_reason": "업체명: 컴포즈"
    },
    {
      "title": "노브랜드버거 부산해운대 장산역점 평일오후 주니어파트너 모집",
      "company": "노브랜드버거 부산장산역점",
      "location": "부산 해운대구 좌동",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,320원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116114324",
      "source": "알바몬",
      "_exclude_reason": "업체명: 노브랜드버거"
    },
    {
      "title": "컴포즈커피 거제옥포시장점 월화 미들3시간 파트타이머 모집합니다.",
      "company": "컴포즈커피 거제옥포시장점",
      "location": "경남 거제시 옥포동",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,320원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116285161",
      "source": "알바몬",
      "_exclude_reason": "업체명: 컴포즈"
    },
    {
      "title": "평일 미들 모집",
      "company": "컴포즈커피 광주주월호반점",
      "location": "광주 남구 주월동",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,320원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116180668",
      "source": "알바몬",
      "_exclude_reason": "업체명: 컴포즈"
    },
    {
      "title": "CJ올리브영 학동중앙점 평일 마감 CREW 구인 (요일협의)",
      "company": "씨제이올리브영 주식회사",
      "location": "서울 강남구 논현동",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116262878",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "[코엑스] 올리브영 코엑스몰점 토일월화 마감 CREW 구인",
      "company": "씨제이올리브영 주식회사 코엑스몰점",
      "location": "서울 강남구",
      "deadline": "2026-05-07",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116168307",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "[코엑스/삼성역]올리브영 파르나스삼성 타운 평일/주말 마감 CREW 구인",
      "company": "씨제이올리브영 주식회사",
      "location": "서울 강남구 신사동",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116333681",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "올리브영 해운대중앙점 평일마감 CREW 구인",
      "company": "씨제이올리브영 주식회사",
      "location": "부산 해운대구 중동",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116341540",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "올리브영 역삼중앙점 주말오픈 CREW 구인",
      "company": "씨제이올리브영 주식회사",
      "location": "서울 강남구",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116145986",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "컴포즈커피  마산롯데점 평일.주말",
      "company": "컴포즈커피 마산롯데점",
      "location": "경남 창원시 마산합포구",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,320원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116338341",
      "source": "알바몬",
      "_exclude_reason": "업체명: 컴포즈"
    },
    {
      "title": "올리브영 광주장덕점 평일 마감 CREW 구인",
      "company": "씨제이올리브영 주식회사",
      "location": "광주 광산구",
      "deadline": "2026-05-08",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116279790",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "올리브영N 성수 주말 오픈 /평일, 주말 마감 CREW 구인",
      "company": "씨제이올리브영 주식회사",
      "location": "서울 중랑구",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116275000",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "컴포즈 창동어울림점에서 함께 일하실 화수목금 마감 아르바이트 모집합니다",
      "company": "컴포즈커피 창동어울림점",
      "location": "서울 도봉구 창동",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,320원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116324419",
      "source": "알바몬",
      "_exclude_reason": "업체명: 컴포즈"
    },
    {
      "title": "올리브영 부산역사점 토일 마감 CREW 구인",
      "company": "씨제이올리브영 주식회사",
      "location": "부산 부산진구",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116318448",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "[직영점/마감 홀청소X] 투썸플레이스 양재매헌역점 스탭(STAFF) 채용",
      "company": "투썸플레이스 양재매헌역점",
      "location": "서울 서초구 양재동",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,400원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116142799",
      "source": "알바몬",
      "_exclude_reason": "업체명: 투썸플레이스"
    },
    {
      "title": "[직영점] 투썸플레이스 삼호가든사거리점 월급제 캡틴 (CAPTAIN)모집",
      "company": "투썸플레이스 삼호가든사거리점",
      "location": "서울 서초구",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "월급 2,500,000원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116233693",
      "source": "알바몬",
      "_exclude_reason": "업체명: 투썸플레이스"
    },
    {
      "title": "컴포즈커피 안산고대병원점 평일 오픈(월화)구합니다.",
      "company": "컴포즈커피 안산고대병원점",
      "location": "경기 안산시 단원구 고잔동",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,320원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116109418",
      "source": "알바몬",
      "_exclude_reason": "업체명: 컴포즈"
    },
    {
      "title": "[컴포즈커피 광주주월호반점] 매니저 모집",
      "company": "컴포즈커피 광주주월호반점",
      "location": "광주 남구 주월동",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "월급 2,350,000원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116180660",
      "source": "알바몬",
      "_exclude_reason": "업체명: 컴포즈"
    },
    {
      "title": "[맥도날드청주봉명점] 청주맛집 봉명점에서 신나게빅맥 만드실 크루 대.모.집",
      "company": "맥도날드 청주 봉명 DT점",
      "location": "충북 청주시 흥덕구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143701235&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "자유로운 스케줄근무 맥도날드 서울시청점에서 함께 근무할 직원 모집합니다",
      "company": "맥도날드 서울 시청점",
      "location": "서울 중구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143724770&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "맥도날드진주혁신DT점 전 시간대 채용합니다.",
      "company": "맥도날드 진주혁신GSDT점",
      "location": "경남 진주시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143897369&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "롯데리아 오포점(양벌) 알바생 모집 (단기알바 x,주말포함가능자)",
      "company": "롯데리아 광주오포점",
      "location": "경기 광주시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143758648&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "버거킹 동두천DT점 주5회 16-23시 금토일 18-25시 크루 모집합니다.",
      "company": "버거킹 동두천DT점",
      "location": "경기 동두천시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143713654&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 버거킹"
    },
    {
      "title": "근로복지 최고, 강남메카~ 압구정역점 알바모집(리아 경력 최고대우)",
      "company": "롯데리아 압구정역",
      "location": "서울 전체",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143899955&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "[카페/오후/직영점]엔제리너스 롯데백화점 동탄점 알바 모집",
      "company": "엔제리너스 롯데백화점 동탄점",
      "location": "경기 화성시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143919629&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 엔제리너스"
    },
    {
      "title": "[부산 수영구] 부산남천DT점 메인터넌스 채용합니다.",
      "company": "맥도날드 부산 남천 DT점",
      "location": "부산 수영구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143821269&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "[급] 이천증포점에서 아르바이트생모집합니다.",
      "company": "롯데리아 이천증포점",
      "location": "경기 이천시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143758643&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "스타벅스 서귀포올레점 바리스타 모집",
      "company": "스타벅스 서귀포올레",
      "location": "제주 서귀포시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143914277&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "주말구인합니다",
      "company": "롯데리아 창원감계점",
      "location": "경남 창원시 의창구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143734594&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "[직영] 투썸플레이스 강동성심병원점 캡틴(CAPTAIN)채용",
      "company": "투썸플레이스(주)",
      "location": "서울 강동구",
      "deadline": "",
      "type": "시간제",
      "salary": "월급 2500000",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143771747&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 투썸플레이스"
    },
    {
      "title": "롯데리아 마석점에서 경력직원 및 알바 모집.프랜차이즈 경력자우선 채용.",
      "company": "롯데리아 마석",
      "location": "경기 남양주시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143724741&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "화성봉담DT점 6-1 5크루 채용합니다(유동적 스케줄 완전 가능)",
      "company": "맥도날드 화성 봉담DT점",
      "location": "경기 화성시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143686319&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "맥도날드 김포장기DT 크루 모집 (평일&주말 전시간 구인)",
      "company": "맥도날드 김포 장기 DT점",
      "location": "경기 김포시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143821262&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "아르바이트생 구합니다",
      "company": "롯데리아 공주신관점",
      "location": "충남 공주시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143919620&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "[부산 수영구] 부산남천DT점 평일/주말크루 채용합니다.",
      "company": "맥도날드 부산 남천 DT점",
      "location": "부산 수영구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143821259&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "[전시간대]출퇴근시간,요일 조정가능/햄버거식사/편하게문의주세요/택시비제공",
      "company": "버거킹 종합운동장사거리점",
      "location": "서울 송파구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143901606&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 버거킹"
    },
    {
      "title": "롯데리아 신호매실점 아르바이트 모집합니다 (문자지원)",
      "company": "롯데리아 신호매실",
      "location": "경기 수원시 권선구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143831428&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "롯데리아 사당역점에서 같이일할 메이트 모집합니다",
      "company": "롯데리아 사당역",
      "location": "서울 동작구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143884625&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "롯데리아 진해용원점 아르바이트(주간, 야간) 모집",
      "company": "롯데리아 진해용원점",
      "location": "경남 창원시 진해구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143863868&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "[맥도날드 여주DT점] 여주DT점과 함께 일할 크루님 모십니다.",
      "company": "맥도날드 여주DT점",
      "location": "경기 여주시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143661858&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "[울산 남구]맥도날드 울산옥동DT점 크루/메인터넌스 모집합니다.",
      "company": "맥도날드 울산 옥동 DT점",
      "location": "울산 남구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143899940&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "롯데리아 산남점 알바모집합니다/",
      "company": "롯데리아 청주산남",
      "location": "충북 청주시 서원구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143907133&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "롯데리아 수원당수점 (평일주말포함)아르바이트 모집합니다.대학생,주부 가능",
      "company": "롯데리아 수원당수",
      "location": "경기 수원시 권선구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143804867&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "스타벅스 광안리점 바리스타 모집",
      "company": "스타벅스 광안리",
      "location": "부산 수영구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143901603&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "[서귀포 신시가지]맥도날드 월드컵DT점에서 크루를 모집합니다.",
      "company": "맥도날드 제주월드컵스타디움DT",
      "location": "제주 서귀포시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143752923&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "NEW AI추천 롯데리아 여수웅천 [아르바이트] 모집",
      "company": "롯데리아 여수웅천지구점",
      "location": "전남 여수시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143652202&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "롯데리아 사당역점에서 같이일하실 부점장님 모집합니다~",
      "company": "롯데리아 사당역",
      "location": "서울 관악구",
      "deadline": "",
      "type": "시간제",
      "salary": "월급 3000000",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143884616&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "스타벅스 수지구청역점 바리스타 모집",
      "company": "스타벅스 수지구청역",
      "location": "경기 용인시 수지구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143734576&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "맥도날드 야탑뉴코아점 함께 성장할 크루 모집합니다 즐겁게 일하고싶은분 환영",
      "company": "맥도날드 야탑 뉴코아점",
      "location": "경기 성남시 분당구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143775798&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "[인센티브 지급] 롯데리아 서울역사점 MATE 모집",
      "company": "롯데리아 서울역사점",
      "location": "서울 전체",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143783741&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "+급구 맥도날드 동수원 (광교) 평일 주말 모든시간 급 모집 +",
      "company": "맥도날드 동수원 GS점",
      "location": "경기 수원시 영통구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143804796&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "스타벅스 오창호수공원점 바리스타 모집",
      "company": "스타벅스 오창호수공원",
      "location": "충북 청주시 청원구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143798904&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "스타벅스 [화성보통저수지점] 에서 함께 일할 바리스타를 모집합니다.",
      "company": "스타벅스 화성보통저수지",
      "location": "경기 화성시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143652147&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "[제주시 이도] 맥도날드 제주 시청점에서 함께 근무할 크루를 모집합니다.",
      "company": "맥도날드 제주 시청 DT점",
      "location": "제주 제주시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143652133&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "롯데리아 보라매타운점에서 아르바이트생 모집합니다.",
      "company": "롯데리아 보라매타운점",
      "location": "서울 동작구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143652132&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "투썸 판교봇들마을점 토일 마감 스텝 구합니다.",
      "company": "투썸플레이스 판교봇들마을점",
      "location": "경기 성남시 분당구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143922223&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 투썸플레이스"
    },
    {
      "title": "[+전시간채용+][초보환영][누구나]강남구청 맥도날드에서 전시간대채용중입니다",
      "company": "맥도날드 강남구청역점",
      "location": "서울 강남구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143922211&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "[서귀포 일호광장]맥도날드 서귀포점에서 즐겁게 일할 분을 모집합니다",
      "company": "맥도날드 서귀포 DT점",
      "location": "제주 서귀포시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143912690&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "[금천구 가산동]맥도날드 가산디지털점에서 함께 근무하실 분을 구합니다",
      "company": "맥도날드 가산 디지털점",
      "location": "서울 금천구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143912689&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "롯데리아 한남대점에서 주말오전 아르바이트 모집합니다.",
      "company": "롯데리아 한남대",
      "location": "대전 대덕구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143899921&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "(중문 제주 서귀포)맥도날드 제주중문DT점에서 함께 일할 크루 모집 합니다",
      "company": "맥도날드 제주중문 DT점",
      "location": "제주 서귀포시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143899920&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "전화x 문자문의 롯데리아 몽촌토성역점 부점장, 바이스 모집합니다",
      "company": "롯데리아 몽촌토성역",
      "location": "서울 광진구",
      "deadline": "",
      "type": "시간제",
      "salary": "월급 3200000",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143884595&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "[평일 오후,주말 오전, 오후 근무] 롯데리아 평택청북점 메이트 모집합니다.",
      "company": "롯데리아 평택청북",
      "location": "경기 평택시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143884585&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "롯데리아 평택 청북점 정규직 직원모집합니다.(경력자 우대)",
      "company": "롯데리아 평택청북점",
      "location": "경기 전체",
      "deadline": "",
      "type": "시간제",
      "salary": "월급 2000000",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143884583&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "[버거킹 안양중앙시장점] 신규오픈 전시간대 근무자 구해용",
      "company": "버거킹 안양중앙시장점",
      "location": "경기 안양시 만안구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143874830&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 버거킹"
    },
    {
      "title": "[서울시 동작구] 맥도날드 숭실대점에서 오후시간 크루 모집합니다.",
      "company": "맥도날드 숭실대점",
      "location": "서울 동작구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143845801&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "[경상북도 구미] 맥도날드 구미인동DT점에서 야간크루를 모집합니다.",
      "company": "맥도날드 구미 인동 DT점",
      "location": "경북 구미시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143839590&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "맥도날드 부산대2호점 크루 모집합니다.",
      "company": "맥도날드 부산대 II점",
      "location": "부산 금정구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143837113&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "[주25h]스타벅스 대구수성네거리DT점에서 함께 일할 바리스타를 모집합니다.",
      "company": "스타벅스 대구수성네거리DT",
      "location": "대구 수성구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143827027&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "[울산삼산점] 버거킹 울산삼산점 크루 대모집",
      "company": "버거킹 울산삼산점",
      "location": "울산 남구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143821228&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 버거킹"
    },
    {
      "title": "롯데리아 청주가경 직원, 알바 채용",
      "company": "롯데리아 청주가경",
      "location": "충북 청주시 흥덕구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143813830&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "[천안불당DT점] 주 25시간 함께할 바리스타를 모집합니다.",
      "company": "스타벅스 천안불당DT",
      "location": "충남 천안시 서북구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143778642&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "[북수원DT점] 맥도날드와 함께할 크루를 모집합니다",
      "company": "맥도날드 북수원 DT점",
      "location": "경기 수원시 장안구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143778638&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "[가양역점] 버거킹 알바 폼 미쳤다",
      "company": "버거킹 가양역점",
      "location": "서울 강서구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143771719&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 버거킹"
    },
    {
      "title": "[서울 종로구]서울동묘역점에서 함께 일하실 크루 모집합니다.",
      "company": "맥도날드 서울 동묘역점",
      "location": "서울 종로구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143771710&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "롯데리아 경력 모집",
      "company": "롯데리아 수원호매실",
      "location": "경기 수원시 권선구",
      "deadline": "",
      "type": "시간제",
      "salary": "월급 2300000",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143771707&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "버거킹걸포점 오후 및 마감 근무자 대환영",
      "company": "버거킹 김포걸포점(S)",
      "location": "경기 김포시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143758582&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 버거킹"
    },
    {
      "title": "여러분 저 했어요~요새 HOT 하다는 롯데리아 지원이요.(문자지원O,전화O)",
      "company": "롯데리아 장한평역점",
      "location": "서울 동대문구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143748248&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "인천공항 T2 3F점에서 평일,주말 근무할 분 모집합니다[교통비+추가수당지급",
      "company": "엔제리너스 인천공항 T1 1F점",
      "location": "인천 중구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143743106&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 엔제리너스"
    },
    {
      "title": "롯데리아 원평점 아르바이트 (주간 야간 근무 가능)",
      "company": "롯데리아 구미원평",
      "location": "경북 구미시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143738381&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "스타벅스 판교놀유니버스점 바리스타 모집",
      "company": "스타벅스 판교놀유니버스",
      "location": "경기 성남시 수정구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143719382&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "[버거킹 안양호계점] 평일 주말 근무자 모집합니다",
      "company": "버거킹 안양호계점",
      "location": "경기 안양시 동안구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143705751&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 버거킹"
    },
    {
      "title": "[서초구] 맥도날드 양재SK DT점에서 함께 근무하실 크루 모집합니다",
      "company": "맥도날드 양재 SK DT점",
      "location": "서울 서초구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143705747&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "맥도날드 목포 하당DT점에서 크루를 모집합니다.",
      "company": "맥도날드 목포하당DT",
      "location": "전남 목포시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143695538&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "[ 롯데리아 별내신도시점 아르바이트 모집 ]",
      "company": "롯데리아 별내신도시점",
      "location": "경기 남양주시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143688912&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "롯데리아인천동암남부 관리자 모집! 수당포함 280만 이상!",
      "company": "롯데리아 동암남부점",
      "location": "인천 부평구",
      "deadline": "",
      "type": "시간제",
      "salary": "월급 2400000",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143688911&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "투썸플레이스 강동길동역점에서 마감스텝 구합니다.",
      "company": "투썸플레이스 강동길동역점",
      "location": "서울 강동구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143686270&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 투썸플레이스"
    },
    {
      "title": "[부산 동구] 맥도날드 범일SKDT점에서 함께 할 크루를 모집합니다.",
      "company": "맥도날드 범일 SK DT점",
      "location": "부산 동구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143680429&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "스타벅스 광주방림DT점 바리스타 채용",
      "company": "스타벅스 광주방림DT",
      "location": "광주 전체",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143675421&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "[엔제리너스 롯데백화점 동탄점]카페 알바 모집 [직영점]",
      "company": "엔제리너스 롯데백화점 동탄점",
      "location": "경기 화성시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143675420&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 엔제리너스"
    },
    {
      "title": "[맥도날드 동탄SK점] 곧 채용마감서두르지 않으면 놓치는 꿀 알바",
      "company": "맥도날드 동탄 SK점",
      "location": "경기 화성시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143646218&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "[맥도날드 동탄SK점] 즐겁고 신나게 빅맥 만드실 크루 모.집",
      "company": "맥도날드 동탄 SK점",
      "location": "경기 화성시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143646217&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "[주3회 이상 근무/6개월 이상 근무] 맥도날드 오리역점 마감 크루 모집",
      "company": "맥도날드 오리역점",
      "location": "경기 성남시 분당구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143646216&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "원주기업도시점 버거킹 매니저 모집 (정규직)",
      "company": "버거킹 원주기업도시점(S)",
      "location": "강원 원주시",
      "deadline": "",
      "type": "시간제",
      "salary": "월급 2360000",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143917171&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 버거킹"
    },
    {
      "title": "원주기업도시버거킹 주말 및 평일 아르바이트 모집 (연령 무관)",
      "company": "버거킹 원주기업도시점(S)",
      "location": "강원 원주시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143917170&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 버거킹"
    },
    {
      "title": "스타벅스 하남미사점에서 함께 근무할 바리스타를 찾습니다.",
      "company": "스타벅스 하남미사",
      "location": "경기 하남시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143917158&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "[직영점]김해내외D/I점 메이트 모집합니다(주말+평일 ~23시까지)",
      "company": "롯데리아 김해내외D/I점",
      "location": "경남 김해시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143916533&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "[아산시, 천안시]맥도날드 아산탕정DT점에서 근무을 함께할 크루를 모집합니다",
      "company": "맥도날드 아산탕정DT점",
      "location": "충남 아산시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143916303&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "세븐일레븐 롯데월드광장점에서 주말 마감 근무자를 구인합니다.",
      "company": "세븐일레븐 롯데월드광장점",
      "location": "서울 송파구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143907102&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 세븐일레븐"
    },
    {
      "title": "세븐일레븐 롯데월드어드벤처점 주말 오후 근무자를 구합니다.",
      "company": "세븐일레븐 롯데월드어드벤처점",
      "location": "서울 송파구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143907098&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 세븐일레븐"
    },
    {
      "title": "세븐일레븐 롯데월드어드벤처점 금토일 근무자를 구합니다.",
      "company": "세븐일레븐 롯데월드어드벤처점",
      "location": "서울 송파구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143907097&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 세븐일레븐"
    },
    {
      "title": "스타벅스 수내로점 바리스타 모집",
      "company": "스타벅스 수내로",
      "location": "경기 성남시 분당구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143904641&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "할리스커피 KG타워점 파트타이머 모십니다",
      "company": "할리스커피 KG타워점",
      "location": "서울 중구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10500",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143894883&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 할리스"
    },
    {
      "title": "행담도휴게소 세븐일레븐 주멀 근무자 구합니다.",
      "company": "세븐일레븐 행담도휴게소(상)점",
      "location": "충남 당진시",
      "deadline": "",
      "type": "시간제",
      "salary": "일급 144000",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143894876&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 세븐일레븐"
    },
    {
      "title": "투썸플레이스 성당점 정직원 모집",
      "company": "투썸플레이스 대구성당점",
      "location": "대구 달서구",
      "deadline": "",
      "type": "시간제",
      "salary": "월급 2450000",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143855947&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 투썸플레이스"
    },
    {
      "title": "[마감타임]햄버거식사-택시비제공/근무시간,요일조정가능/편하게문의주세요",
      "company": "버거킹 수서점",
      "location": "서울 강남구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143855939&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 버거킹"
    },
    {
      "title": "용돈 걱정 끝 리아 소공2호 알바 구해요",
      "company": "롯데리아 소공2호점",
      "location": "서울 전체",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143855937&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "2026년 Web(java) 개발자 채용",
      "company": "주식회사거룡아이티",
      "location": "경기 고양시 덕양구",
      "deadline": "2026-05-03",
      "type": "",
      "salary": "",
      "description": "",
      "apply_link": "http://www.work.go.kr/empInfo/empInfoSrch/detail/empDetailAuthView.do?callPage=detail&wantedAuthNo=K180212604170027",
      "source": "시니어로",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "(주)아르비젼 연구소 임베디드 소프트웨어 개발자 ...",
      "company": "(주)아르비젼",
      "location": "(08591) 서울특별시 금천구 가산디지털1로 2 317호",
      "deadline": "상시모집",
      "type": "",
      "salary": "(연봉) 3100만원 ~ 3800만원",
      "description": "",
      "apply_link": "https://job.seoul.go.kr/hmpg/rmim/rcmg/rcmgDetail.do?wantedAuthNo=K120612604300022",
      "source": "서울일자리포털",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "응용 소프트웨어 개발자",
      "company": "케이포시큐리티(주)",
      "location": "(08382) 서울특별시 구로구 디지털로 243 서울특별시 구로구 디지털로 243 (지하이시티)",
      "deadline": "26-05-23",
      "type": "",
      "salary": "(연봉) 2700만원 ~ 6000만원",
      "description": "",
      "apply_link": "https://job.seoul.go.kr/hmpg/rmim/rcmg/rcmgDetail.do?wantedAuthNo=K120612604300017",
      "source": "서울일자리포털",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "(주)싸이크로스Web/App 개발자 경력사원 모집",
      "company": "(주)싸이크로스",
      "location": "(06300) 서울특별시 강남구 양재천로 191 동화빌딩 2층",
      "deadline": "상시모집",
      "type": "",
      "salary": "(연봉) 4000만원",
      "description": "",
      "apply_link": "https://job.seoul.go.kr/hmpg/rmim/rcmg/rcmgDetail.do?wantedAuthNo=K120032604280034",
      "source": "서울일자리포털",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "(주)싸이크로스Web/App 개발자 신입사원 모집",
      "company": "(주)싸이크로스",
      "location": "(06300) 서울특별시 강남구 양재천로 191 동화빌딩 2층",
      "deadline": "상시모집",
      "type": "",
      "salary": "(연봉) 3000만원 ~ 3400만원",
      "description": "",
      "apply_link": "https://job.seoul.go.kr/hmpg/rmim/rcmg/rcmgDetail.do?wantedAuthNo=K120032604280033",
      "source": "서울일자리포털",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "디저트 브랜드 디자이너",
      "company": "주식회사 건솔현",
      "location": "(07791) 서울특별시 강서구 마곡동로10길 46 218",
      "deadline": "26-05-13",
      "type": "",
      "salary": "(연봉) 2700만원 ~ 3100만원",
      "description": "",
      "apply_link": "https://job.seoul.go.kr/hmpg/rmim/rcmg/rcmgDetail.do?wantedAuthNo=K120412604280012",
      "source": "서울일자리포털",
      "_exclude_reason": "키워드: 브랜드 디자이너"
    },
    {
      "title": "[커피빈코리아] 여의도/강서지역 슈퍼바이저(바리스...",
      "company": "(주)커피빈코리아",
      "location": "(06087) 서울특별시 강남구 봉은사로99길 7 7 거주지, 희망지역 반영하여 1시간 이내 거리 발령(매장TO반영)",
      "deadline": "상시모집",
      "type": "",
      "salary": "(월급) 240만원 ~ 240만원",
      "description": "",
      "apply_link": "https://job.seoul.go.kr/hmpg/rmim/rcmg/rcmgDetail.do?wantedAuthNo=KJAF002604270022",
      "source": "서울일자리포털",
      "_exclude_reason": "업체명: 커피빈"
    },
    {
      "title": "[커피빈코리아 선릉로93길점] 슈퍼바이저(바리스타...",
      "company": "(주)커피빈코리아",
      "location": "(06149) 서울특별시 강남구 선릉로93길 6 .",
      "deadline": "상시모집",
      "type": "",
      "salary": "(월급) 240만원 ~ 240만원",
      "description": "",
      "apply_link": "https://job.seoul.go.kr/hmpg/rmim/rcmg/rcmgDetail.do?wantedAuthNo=KJAF002604270021",
      "source": "서울일자리포털",
      "_exclude_reason": "업체명: 커피빈"
    },
    {
      "title": "커피빈 코엑스웨스틴서울점 슈퍼바이저",
      "company": "(주)커피빈코리아",
      "location": "(06164) 서울특별시 강남구 봉은사로 524 커피빈 코엑스웨스틴서울점",
      "deadline": "상시모집",
      "type": "",
      "salary": "(월급) 240만원 ~ 240만원",
      "description": "",
      "apply_link": "https://job.seoul.go.kr/hmpg/rmim/rcmg/rcmgDetail.do?wantedAuthNo=KJAF002604270018",
      "source": "서울일자리포털",
      "_exclude_reason": "업체명: 커피빈"
    },
    {
      "title": "[커피빈코리아] 삼성봉은사로점 슈퍼바이져",
      "company": "(주)커피빈코리아",
      "location": "(06170) 서울특별시 강남구 봉은사로 628 커피빈 삼성봉은사로점",
      "deadline": "상시모집",
      "type": "",
      "salary": "(월급) 240만원 ~ 240만원",
      "description": "",
      "apply_link": "https://job.seoul.go.kr/hmpg/rmim/rcmg/rcmgDetail.do?wantedAuthNo=KJAF002604270016",
      "source": "서울일자리포털",
      "_exclude_reason": "업체명: 커피빈"
    },
    {
      "title": "[커피빈코리아] 서울 슈퍼바이저(바리스타) 채용 ...",
      "company": "(주)커피빈코리아",
      "location": "(06149) 서울특별시 강남구 선릉로93길 6",
      "deadline": "상시모집",
      "type": "",
      "salary": "(월급) 140만원 ~ 140만원",
      "description": "",
      "apply_link": "https://job.seoul.go.kr/hmpg/rmim/rcmg/rcmgDetail.do?wantedAuthNo=KJAF002604270015",
      "source": "서울일자리포털",
      "_exclude_reason": "업체명: 커피빈"
    },
    {
      "title": "[커피빈 선릉/논현지역] 바리스타(슈퍼바이저) 채...",
      "company": "(주)커피빈코리아",
      "location": "(06087) 서울특별시 강남구 봉은사로99길 7 커피빈코리아",
      "deadline": "26-06-26",
      "type": "",
      "salary": "(월급) 240만원 ~ 240만원",
      "description": "",
      "apply_link": "https://job.seoul.go.kr/hmpg/rmim/rcmg/rcmgDetail.do?wantedAuthNo=KJAF002604270013",
      "source": "서울일자리포털",
      "_exclude_reason": "업체명: 커피빈"
    },
    {
      "title": "[커피빈코리아] 커피빈 서울대입구역 슈퍼바이저(바...",
      "company": "(주)커피빈코리아",
      "location": "(08787) 서울특별시 관악구 관악로 161 커피빈서울대입구역점",
      "deadline": "상시모집",
      "type": "",
      "salary": "(월급) 240만원 ~ 240만원",
      "description": "",
      "apply_link": "https://job.seoul.go.kr/hmpg/rmim/rcmg/rcmgDetail.do?wantedAuthNo=KJAF002604270012",
      "source": "서울일자리포털",
      "_exclude_reason": "업체명: 커피빈"
    },
    {
      "title": "피부.미용 의료기기 기술 개발자 모집",
      "company": "(주)스타로닉",
      "location": "(07378) 서울특별시 영등포구 가마산로 337 스타로닉빌딩",
      "deadline": "26-05-17",
      "type": "",
      "salary": "(연봉) 4000만원 ~ 4500만원",
      "description": "",
      "apply_link": "https://job.seoul.go.kr/hmpg/rmim/rcmg/rcmgDetail.do?wantedAuthNo=K120422604270016",
      "source": "서울일자리포털",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "임베디드 및 소프트웨어 개발자 모집",
      "company": "코리아디지탈(주)",
      "location": "(08381) 서울특별시 구로구 디지털로 273 804호",
      "deadline": "상시모집",
      "type": "",
      "salary": "(연봉) 2800만원 ~ 5000만원",
      "description": "",
      "apply_link": "https://job.seoul.go.kr/hmpg/rmim/rcmg/rcmgDetail.do?wantedAuthNo=KF11042604240001",
      "source": "서울일자리포털",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "제품 시각/그래픽 디자이너 채용공고",
      "company": "주식회사 멜로우스페이스",
      "location": "하남시",
      "deadline": "2026-04-30",
      "type": "정규직",
      "salary": "연봉 2600만원 ~ 3800만원",
      "description": "",
      "apply_link": "http://www.work.go.kr/empInfo/empInfoSrch/detail/empDetailAuthView.do?wantedAuthNo=K180342604010010",
      "source": "잡아바",
      "_exclude_reason": "키워드: 그래픽 디자이너"
    },
    {
      "title": "원평산업(주) 생산직 모집 /2교대/병역특례 지원...",
      "company": "원평산업(주)",
      "location": "안산시",
      "deadline": "2026-05-02",
      "type": "정규직",
      "salary": "시급 10520원 ~ 10520원",
      "description": "",
      "apply_link": "http://www.work.go.kr/empInfo/empInfoSrch/detail/empDetailAuthView.do?wantedAuthNo=KJKP002603030019",
      "source": "잡아바",
      "_exclude_reason": "키워드: 병역특례"
    },
    {
      "title": "2026년 Web(java) 개발자 채용",
      "company": "(주)거룡아이티",
      "location": "고양시",
      "deadline": "2026-05-03",
      "type": "계약직",
      "salary": "연봉 3000만원 ~ 5000만원",
      "description": "",
      "apply_link": "http://www.work.go.kr/empInfo/empInfoSrch/detail/empDetailAuthView.do?wantedAuthNo=K180212604170027",
      "source": "잡아바",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "자동차 안전밸트 관련 생산직 모집/2교대/병역특례...",
      "company": "풍국기업(주)",
      "location": "안산시",
      "deadline": "2026-05-02",
      "type": "정규직",
      "salary": "시급 10520원 ~ 10520원",
      "description": "",
      "apply_link": "http://www.work.go.kr/empInfo/empInfoSrch/detail/empDetailAuthView.do?wantedAuthNo=KJKP002603030021",
      "source": "잡아바",
      "_exclude_reason": "키워드: 병역특례"
    },
    {
      "title": "2026년 상반기 HRD/조직문화 채용연계형 인턴 모집",
      "company": "SK가스(주)",
      "location": "성남시",
      "deadline": "2026-05-10",
      "type": "",
      "salary": "",
      "description": "",
      "apply_link": "https://www.jobkorea.co.kr/Recruit/GI_Read/49074786?Oem_Code=C900&api=232",
      "source": "잡아바",
      "_exclude_reason": "키워드: 채용연계형 인턴"
    },
    {
      "title": "소스류 및 식품 개발자 초빙",
      "company": "(주)우복당식품",
      "location": "안양시",
      "deadline": "2026-05-24",
      "type": "정규직",
      "salary": "연봉 4000만원 ~ 5000만원",
      "description": "",
      "apply_link": "http://www.work.go.kr/empInfo/empInfoSrch/detail/empDetailAuthView.do?wantedAuthNo=K180032603250034",
      "source": "잡아바",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "AI 개발자 모집 프리랜서",
      "company": "(주)누리인포스",
      "location": "성남시,수원시",
      "deadline": "2026-05-28",
      "type": "",
      "salary": "",
      "description": "",
      "apply_link": "https://www.jobkorea.co.kr/Recruit/GI_Read/49074628?Oem_Code=C900&api=232",
      "source": "잡아바",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "[픽플러스] 프론트엔드/백엔드 개발자 경력자 채용",
      "company": "(주)픽플러스",
      "location": "고양시",
      "deadline": "2026-05-28",
      "type": "계약직",
      "salary": "",
      "description": "",
      "apply_link": "https://www.jobkorea.co.kr/Recruit/GI_Read/49075303?Oem_Code=C900&api=232",
      "source": "잡아바",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "[판교/글로벌기업] 백엔드 개발자 (Java/팀원)",
      "company": "(주)이파피루스",
      "location": "성남시",
      "deadline": "2026-05-28",
      "type": "",
      "salary": "",
      "description": "",
      "apply_link": "https://www.jobkorea.co.kr/Recruit/GI_Read/49075656?Oem_Code=C900&api=232",
      "source": "잡아바",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "2026 로밍도깨비 퍼포먼스 마케터 담당자 모집",
      "company": "유엔젤(주)",
      "location": "성남시",
      "deadline": "2026-05-29",
      "type": "",
      "salary": "",
      "description": "",
      "apply_link": "https://www.jobkorea.co.kr/Recruit/GI_Read/49053507?Oem_Code=C900&api=232",
      "source": "잡아바",
      "_exclude_reason": "키워드: 퍼포먼스 마케터"
    },
    {
      "title": "[일반] 그리다 랩_게임 기획 및 게임 스크립트 작성",
      "company": "그리다 랩",
      "location": "부천시",
      "deadline": "2026-08-31",
      "type": "",
      "salary": "3000 ~ 4000 만원",
      "description": "",
      "apply_link": "https://job.gg.go.kr/empmn/jobEntDtl.do?seq=14554",
      "source": "잡아바",
      "_exclude_reason": "키워드: 게임 기획"
    },
    {
      "title": "[일반] 참참바이오 주식회사_풀스텍, 백엔드 개발자",
      "company": "참참바이오 주식회사",
      "location": "화성시",
      "deadline": "2026-08-31",
      "type": "",
      "salary": "3000 ~ 4000 만원",
      "description": "",
      "apply_link": "https://job.gg.go.kr/empmn/jobEntDtl.do?seq=14571",
      "source": "잡아바",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "전기자동차충전기업체 S/W 개발자 모집 2026....",
      "company": "(주)파워큐브코리아",
      "location": "의왕시",
      "deadline": "2026-06-09",
      "type": "계약직",
      "salary": "연봉 3000만원 ~ 6000만원",
      "description": "",
      "apply_link": "http://www.work.go.kr/empInfo/empInfoSrch/detail/empDetailAuthView.do?wantedAuthNo=KJKY002604100004",
      "source": "잡아바",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "[모집] 병역특례 -기계,전기,전자,용접",
      "company": "(주)일신바이오베이스",
      "location": "동두천시",
      "deadline": "2026-06-20",
      "type": "계약직",
      "salary": "연봉 2588만원 ~ 3000만원",
      "description": "",
      "apply_link": "http://www.work.go.kr/empInfo/empInfoSrch/detail/empDetailAuthView.do?wantedAuthNo=K180142604210012",
      "source": "잡아바",
      "_exclude_reason": "키워드: 병역특례"
    },
    {
      "title": "[일반]주식회사 그랜드소프트_풀스택 개발자",
      "company": "주식회사 그랜드소프트",
      "location": "성남시",
      "deadline": "2026-08-31",
      "type": "",
      "salary": "3000 ~ 4000 만원",
      "description": "",
      "apply_link": "https://job.gg.go.kr/empmn/jobEntDtl.do?seq=14609",
      "source": "잡아바",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "카메라 모듈 검사 Firmware 개발자 모집",
      "company": "(주)다람기술",
      "location": "평택시",
      "deadline": "2026-06-12",
      "type": "정규직",
      "salary": "월급 220만원 ~ 240만원",
      "description": "",
      "apply_link": "http://www.work.go.kr/empInfo/empInfoSrch/detail/empDetailAuthView.do?wantedAuthNo=K180612604140003",
      "source": "잡아바",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "Java MES 개발자 - 스마트팩토리 경력자 모집 (Python, AI 경력우대)",
      "company": "건솔루션(주)",
      "location": "경기전체,안양시,서울특별시",
      "deadline": "2026-06-30",
      "type": "",
      "salary": "",
      "description": "",
      "apply_link": "https://www.jobkorea.co.kr/Recruit/GI_Read/49074461?Oem_Code=C900&api=232",
      "source": "잡아바",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "[일반] 주식회사 그랜드소프트_ 개발자",
      "company": "주식회사 그랜드소프트",
      "location": "성남시",
      "deadline": "2026-08-31",
      "type": "",
      "salary": "3000 ~ 4000 만원",
      "description": "",
      "apply_link": "https://job.gg.go.kr/empmn/jobEntDtl.do?seq=14611",
      "source": "잡아바",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "[북부특화] 주식회사 케어클_퍼포먼스 마케터",
      "company": "주식회사 케어클",
      "location": "고양시",
      "deadline": "2026-08-31",
      "type": "",
      "salary": "2500 ~ 3000 만원",
      "description": "",
      "apply_link": "https://job.gg.go.kr/empmn/jobEntDtl.do?seq=14525",
      "source": "잡아바",
      "_exclude_reason": "키워드: 퍼포먼스 마케터"
    },
    {
      "title": "[일반] (주)우보재난시스템_기술연구소 백엔드 개발",
      "company": "(주)우보재난시스템",
      "location": "성남시",
      "deadline": "2026-08-31",
      "type": "",
      "salary": "3000 ~ 4000 만원",
      "description": "",
      "apply_link": "https://job.gg.go.kr/empmn/jobEntDtl.do?seq=14542",
      "source": "잡아바",
      "_exclude_reason": "키워드: 백엔드"
    },
    {
      "title": "[일반] (주)우보재난시스템_기술연구소 H/W 및 F/W 개발자",
      "company": "(주)우보재난시스템",
      "location": "성남시",
      "deadline": "2026-08-31",
      "type": "",
      "salary": "3000 ~ 4000 만원",
      "description": "",
      "apply_link": "https://job.gg.go.kr/empmn/jobEntDtl.do?seq=14544",
      "source": "잡아바",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "[일반] (주)우보재난시스템_기술연구소 WEB PHP 개발자",
      "company": "(주)우보재난시스템",
      "location": "성남시",
      "deadline": "2026-08-31",
      "type": "",
      "salary": "3000 ~ 4000 만원",
      "description": "",
      "apply_link": "https://job.gg.go.kr/empmn/jobEntDtl.do?seq=14547",
      "source": "잡아바",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "[일반] 주식회사 아이디벨_UI/UX 디자이너",
      "company": "(주)아이디벨",
      "location": "하남시",
      "deadline": "2026-08-31",
      "type": "",
      "salary": "3000 ~ 4000 만원",
      "description": "",
      "apply_link": "https://job.gg.go.kr/empmn/jobEntDtl.do?seq=14657",
      "source": "잡아바",
      "_exclude_reason": "키워드: ui/ux 디자이너"
    },
    {
      "title": "[일반]시큐와우 주식회사_ 연구개발자",
      "company": "시큐와우㈜",
      "location": "안양시",
      "deadline": "2026-08-31",
      "type": "",
      "salary": "3000 ~ 4000 만원",
      "description": "",
      "apply_link": "https://job.gg.go.kr/empmn/jobEntDtl.do?seq=14675",
      "source": "잡아바",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "[일반] (주)레드마우스_프론트엔드개발",
      "company": "(주)레드마우스",
      "location": "화성시",
      "deadline": "2026-08-31",
      "type": "",
      "salary": "3000 ~ 4000 만원",
      "description": "",
      "apply_link": "https://job.gg.go.kr/empmn/jobEntDtl.do?seq=14680",
      "source": "잡아바",
      "_exclude_reason": "키워드: 프론트엔드"
    },
    {
      "title": "[일반] (주)레드마우스_백엔드 개발",
      "company": "(주)레드마우스",
      "location": "화성시",
      "deadline": "2026-08-31",
      "type": "",
      "salary": "3000 ~ 4000 만원",
      "description": "",
      "apply_link": "https://job.gg.go.kr/empmn/jobEntDtl.do?seq=14681",
      "source": "잡아바",
      "_exclude_reason": "키워드: 백엔드"
    }
  ],
  "filter_config": {
    "companies": [
      "24시스포츠",
      "cgv",
      "cu편의점",
      "gs25",
      "kfc",
      "게임빌",
      "공차",
      "넥슨",
      "넷마블",
      "노브랜드버거",
      "더벤티",
      "더피트",
      "던킨",
      "롯데리아",
      "롯데시네마",
      "맘스터치",
      "맥도날드",
      "메가박스",
      "메가커피",
      "무신사",
      "배달의민족",
      "배스킨라빈스",
      "버거킹",
      "브랜디",
      "블루보틀",
      "빽다방",
      "서브웨이",
      "세븐일레븐",
      "쉐이크쉑",
      "스마일게이트",
      "스타벅스",
      "스파오",
      "스포애니",
      "씨네큐",
      "애니타임피트니스",
      "에이블리",
      "엔씨소프트",
      "엔제리너스",
      "올리브영",
      "요기요",
      "위메이드",
      "이디야",
      "이마트24",
      "지그재그",
      "카카오게임즈",
      "카페베네",
      "커피빈",
      "컴투스",
      "컴포즈",
      "쿠팡이츠",
      "크래프톤",
      "크리스피크림",
      "탐앤탐스",
      "탑텐",
      "투썸플레이스",
      "파스쿠찌",
      "파이브가이즈",
      "파파이스",
      "펄어비스",
      "폴바셋",
      "할리스"
    ],
    "keywords": [
      "나이트클럽",
      "유흥주점",
      "단란주점",
      "룸살롱",
      "룸카페",
      "호스트바",
      "바텐더",
      "호프집",
      "맥주집",
      "포장마차",
      "포차",
      "이자카야",
      "pc방",
      "피씨방",
      "코인노래방",
      "10대",
      "20대 초반",
      "나이 제한",
      "개발자",
      "백엔드 개발자",
      "프론트엔드 개발자",
      "풀스택 개발자",
      "프론트엔드",
      "백엔드",
      "풀스택",
      "ios 개발자",
      "android 개발자",
      "앱 개발자",
      "웹 개발자",
      "devops 엔지니어",
      "devops",
      "sre 엔지니어",
      "ui/ux 디자이너",
      "ux 디자이너",
      "ui 디자이너",
      "데이터 사이언티스트",
      "머신러닝 엔지니어",
      "딥러닝 엔지니어",
      "ai 엔지니어",
      "소프트웨어 엔지니어",
      "클라우드 엔지니어",
      "qa 엔지니어",
      "테스트 엔지니어",
      "데이터 분석가",
      "데이터 엔지니어",
      "데이터 사이언스",
      "게임 개발",
      "모바일 개발",
      "앱 개발",
      "프로덕트 매니저",
      "프로덕트 디자이너",
      "게임 pd",
      "웹퍼블리셔",
      "서비스 기획자",
      "it 기획자",
      "node.js",
      "react",
      "vue.js",
      "spring",
      "flutter",
      "kotlin",
      "typescript",
      "python 개발",
      "java 개발",
      "javascript",
      "인공지능 개발",
      "llm",
      "mlops",
      "클라우드 아키텍트",
      "블록체인",
      "web3",
      "nft",
      "병역특례",
      "그래픽 디자이너",
      "브랜드 디자이너",
      "모션 그래픽",
      "모션 디자이너",
      "영상 편집",
      "영상 제작자",
      "영상 pd",
      "3d 디자이너",
      "3d 모델러",
      "3d 아티스트",
      "게임 아티스트",
      "콘셉트 아티스트",
      "캐릭터 디자이너",
      "배경 아티스트",
      "웹툰 작가",
      "만화 작가",
      "게임 기획",
      "게임 디자인",
      "e스포츠",
      "이스포츠",
      "프로게이머",
      "게임 스트리머",
      "유튜브 크리에이터",
      "유튜브 운영",
      "유튜브 편집",
      "틱톡 크리에이터",
      "틱톡 운영",
      "숏폼",
      "릴스 제작",
      "인플루언서",
      "인터넷 방송",
      "스트리머",
      "sns 마케터",
      "콘텐츠 크리에이터",
      "퍼포먼스 마케터",
      "퍼포먼스 마케팅",
      "그로스 마케터",
      "그로스 해킹",
      "seo 마케터",
      "앱 마케터",
      "배달 라이더",
      "배달기사",
      "오토바이 라이더",
      "퀵서비스 라이더",
      "오토바이 배달",
      "새벽 배송 기사",
      "쿠팡 로켓배송",
      "이삿짐",
      "헬스 트레이너",
      "퍼스널 트레이너",
      "pt 트레이너",
      "필라테스 강사",
      "요가 강사",
      "스피닝 강사",
      "인턴십",
      "채용연계형 인턴",
      "대졸 신입 공채",
      "신입 공채",
      "대학생 전용",
      "고등학생 가능"
    ]
  }
};
