/* 자동 생성 — 필터링 제외 목록 / 2026-05-01 23:32:26 KST */
var EXCLUDED_DATA = {
  "updated_at": "2026-05-01 23:32:26 KST",
  "total": 41,
  "jobs": [
    {
      "title": "글로벌 패션 커머스 Node.js 백엔드 개발자 (병역특례 가능)",
      "company": "페칭",
      "location": "서울 성동구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=139191&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 백엔드 개발자"
    },
    {
      "title": "글로벌 패션 커머스 주니어 Node.js 백엔드 개발자 (병역특례 ...",
      "company": "페칭",
      "location": "서울 성동구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력무관 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=234680&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 백엔드 개발자"
    },
    {
      "title": "글로벌 패션 커머스 프론트엔드 개발자 (병역특례 가능)",
      "company": "페칭",
      "location": "서울 성동구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=248170&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 프론트엔드 개발자"
    },
    {
      "title": "글로벌 패션 커머스 UI/UX 디자이너",
      "company": "페칭",
      "location": "서울 성동구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=257235&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: ui/ux 디자이너"
    },
    {
      "title": "글로벌 패션 커머스 프론트엔드 개발자 주니어 (병역 특례 가능)",
      "company": "페칭",
      "location": "서울 성동구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력무관 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=301316&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 프론트엔드 개발자"
    },
    {
      "title": "[미리캔버스] 시니어 프론트엔드 개발자",
      "company": "미리디",
      "location": "지역무관",
      "deadline": "2026-05-22",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=337323&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 프론트엔드 개발자"
    },
    {
      "title": "[미리캔버스] 백엔드 개발자",
      "company": "미리디",
      "location": "지역무관",
      "deadline": "2026-05-22",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=337958&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 백엔드 개발자"
    },
    {
      "title": "글로벌 B2B PM",
      "company": "씨제이올리브영(CJ올리브영)",
      "location": "서울 용산구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=345803&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "풀스택 개발자 (5년+)",
      "company": "네오플랫",
      "location": "서울 마포구",
      "deadline": "2026-05-31",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=354917&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 풀스택 개발자"
    },
    {
      "title": "백엔드 개발자(RDPLINE) 3년 이상",
      "company": "비큐에이아이",
      "location": "지역무관",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=358780&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 백엔드 개발자"
    },
    {
      "title": "[리텐틱스] 데이터 사이언티스트 (Data Scientist) 3년...",
      "company": "프라이데이즈랩(Retentics)",
      "location": "서울 강남구",
      "deadline": "2026-05-30",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=358944&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 데이터 사이언티스트"
    },
    {
      "title": "인플루언서 마케팅/커머스 매니저",
      "company": "왈로우",
      "location": "경기 하남시",
      "deadline": "2026-05-31",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=359060&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 인플루언서"
    },
    {
      "title": "소프트웨어 엔지니어",
      "company": "히포크랏 랩스(Hippocrat Labs)",
      "location": "서울 강남구",
      "deadline": "",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=359171&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 소프트웨어 엔지니어"
    },
    {
      "title": "Python 백엔드 개발자 모집 (잠실 상주, 고급/특급)",
      "company": "단감소프트",
      "location": "지역무관",
      "deadline": "2026-05-05",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=358829&infoTypeCd=CWT&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 백엔드 개발자"
    },
    {
      "title": "신도림동/10대/남/자폐성심한장애/장애인활동지원사",
      "company": "중앙장애인 활동지원센터",
      "location": "서울특별시 구로구 신도림로",
      "deadline": "2026-05-14",
      "type": "",
      "salary": "시급 10,320 원 이상",
      "description": "경력무관 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=K120612604300031&infoTypeCd=VALIDATION&infoTypeGroup=tb_workinfoworknet",
      "source": "고용24",
      "_exclude_reason": "키워드: 10대"
    },
    {
      "title": "롯데리아 수원 금곡점 경력자, 신입 아르바이트 모집(고등학생 가능)",
      "company": "롯데리아 수원금곡점",
      "location": "경기 수원시 권선구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143804563&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "키워드: 고등학생 가능"
    },
    {
      "title": "[할리스진주초전점] 아르바이트 구함 (주2~4회/근무표 매주변동/장기근무)",
      "company": "할리스커피 진주초전점",
      "location": "경남 진주시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143804555&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 할리스"
    },
    {
      "title": "[ 스타벅스 대전월평점]에서 함께 근무할 바리스타를 모집합니다.",
      "company": "스타벅스 대전월평",
      "location": "대전 서구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143780607&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "투썸플레이스 신대점 주말 스텝 모집합니다(토~일)",
      "company": "투썸플레이스(순천신대점)",
      "location": "전남 순천시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143897228&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 투썸플레이스"
    },
    {
      "title": "올리브영 원흥역점 화,목,토 오픈 CREW 모집",
      "company": "씨제이올리브영 주식회사",
      "location": "경기 고양시 일산동구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10600",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143838392&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "스타벅스 청주율량DT점 에서 함께 할 바리스타를 모집합니다.",
      "company": "스타벅스 청주율량DT",
      "location": "충북 전체",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143651851&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "올리브영 제주협재점 금토일 오픈 CREW 구인 (시간협의가능)",
      "company": "씨제이올리브영주식회사",
      "location": "제주 제주시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10600",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143854876&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "[직영점]투썸플레이스 삼호가든사거리점 캡틴(Captain)",
      "company": "투썸플레이스",
      "location": "서울 전체",
      "deadline": "",
      "type": "시간제",
      "salary": "월급 2500000",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143804541&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 투썸플레이스"
    },
    {
      "title": "투썸플레이스 화성동탄점 마감스텝 모집",
      "company": "투썸플레이스 화성동탄점",
      "location": "경기 화성시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143775743&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 투썸플레이스"
    },
    {
      "title": "스타벅스 송도캐슬파크점 바리스타 채용",
      "company": "스타벅스 송도캐슬파크",
      "location": "인천 연수구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143826457&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "[스타벅스 대전판암DT] 함께 즐겁게 일할 바리스타 모집해요",
      "company": "스타벅스 대전판암DT",
      "location": "대전 동구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143821107&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "[울산삼산로점] 함께 근무하실 바리스타 모집합니다.",
      "company": "스타벅스 울산삼산로",
      "location": "울산 전체",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143786224&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "[여주자유CC] 스타벅스 바리스타 채용",
      "company": "스타벅스 여주자유CC",
      "location": "경기 여주시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143615816&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "[스타벅스 창원용지호수점] 주 25시간 바리스타 모집",
      "company": "스타벅스 창원용지호수",
      "location": "경남 창원시 성산구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143879336&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "한신포차 울산구영점 홀서빙 오픈조 모집합니다",
      "company": "더본코리아 한신포차 울산구영점",
      "location": "울산 울주군",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10500",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143622832&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "키워드: 포차"
    },
    {
      "title": "스타벅스 오리역점에서 함께 근무하실 파트너를 모집합니다",
      "company": "스타벅스 오리역",
      "location": "경기 성남시 분당구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143869785&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "투썸플레이스 전주 신시가지점 평일미들스텝 모집합니다.",
      "company": "투썸플레이스 전주신시가지점",
      "location": "전북 전주시 완산구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143826428&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 투썸플레이스"
    },
    {
      "title": "스타벅스 대전중앙로R점 바리스타 모집",
      "company": "스타벅스 대전중앙로R",
      "location": "대전 중구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143798157&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "오리역삼거리에서 함께 근무하실 파트너를 모집합니다",
      "company": "스타벅스 오리역삼거리",
      "location": "경기 성남시 분당구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143798147&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "스타벅스 광주진월점에서 함께하실 바리스타를 모집합니다.",
      "company": "스타벅스 광주진월",
      "location": "광주 남구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143710851&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "[스타벅스세종다정DT점]열정있는 바리스타 모집",
      "company": "스타벅스 세종다정DT",
      "location": "세종 전체",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143899777&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "스타벅스 죽백DT점 바리스타 모집",
      "company": "스타벅스 평택죽백DT",
      "location": "경기 평택시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143884329&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "교통비 지원이 가능한 스타벅스 매장",
      "company": "스타벅스 가평설악IC DT",
      "location": "경기 가평군",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143874265&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "스타벅스 제주칠성점 바리스타 모집",
      "company": "스타벅스 제주칠성",
      "location": "제주 제주시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143850993&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "할리스 일광신도시점에서 재밌게 일하실 마감 파트타이머를 구합니다.",
      "company": "할리스커피 부산일광신도시점",
      "location": "부산 기장군",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143813721&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 할리스"
    },
    {
      "title": "[투썸플레이스] 고양삼송미디어시티점 평일(월~목) 마감 근무 스탭 모집",
      "company": "투썸플레이스 고양삼송미디어시티점",
      "location": "경기 고양시 덕양구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10400",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143804456&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 투썸플레이스"
    }
  ],
  "filter_config": {
    "companies": [
      "cgv",
      "공차",
      "롯데시네마",
      "메가박스",
      "빽다방",
      "스타벅스",
      "씨네큐",
      "올리브영",
      "이디야",
      "컴포즈",
      "탐앤탐스",
      "투썸플레이스",
      "파스쿠찌",
      "폴바셋",
      "할리스"
    ],
    "keywords": [
      "나이트클럽",
      "유흥주점",
      "단란주점",
      "룸살롱",
      "룸카페",
      "호스트바",
      "바텐더",
      "호프집",
      "맥주집",
      "포장마차",
      "포차",
      "이자카야",
      "pc방",
      "피씨방",
      "코인노래방",
      "10대",
      "20대 초반",
      "나이 제한",
      "백엔드 개발자",
      "프론트엔드 개발자",
      "풀스택 개발자",
      "ios 개발자",
      "android 개발자",
      "앱 개발자",
      "devops 엔지니어",
      "ui/ux 디자이너",
      "ux 디자이너",
      "데이터 사이언티스트",
      "머신러닝 엔지니어",
      "딥러닝 엔지니어",
      "ai 엔지니어",
      "소프트웨어 엔지니어",
      "클라우드 엔지니어",
      "유튜브 크리에이터",
      "틱톡 크리에이터",
      "인플루언서",
      "sns 마케터",
      "콘텐츠 크리에이터",
      "이삿짐",
      "퀵서비스 라이더",
      "오토바이 배달",
      "고등학생 가능",
      "대학생 전용"
    ]
  }
};
