/* 자동 생성 — 필터링 제외 목록 / 2026-05-11 07:12:47 KST */
var EXCLUDED_DATA = {
  "updated_at": "2026-05-11 07:12:47 KST",
  "total": 144,
  "jobs": [
    {
      "title": "굿스푼 퍼포먼스 마케터 경력을 구합니다.",
      "company": "(주)미스터네이처",
      "location": "광주 광산구",
      "deadline": "2026-06-09",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력4년 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=53841863&infoTypeCd=CSI&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 퍼포먼스 마케터"
    },
    {
      "title": "[울산-정규직] 공공(금융)  -  (중급)개발자를 모십니다.",
      "company": "트리플랜㈜",
      "location": "울산 중구",
      "deadline": "2026-06-09",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력5년 대졸(2~3년)",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=50862539&infoTypeCd=CJK&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "(주)프리벤터에서 생산 기술 개발자 모집",
      "company": "(주)프리벤터",
      "location": "충남 천안시 동남구 등",
      "deadline": "2026-06-09",
      "type": "",
      "salary": "월급 320 만원 ~ 320 만원",
      "description": "경력무관 대졸(2~3년)",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=53842304&infoTypeCd=CSI&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "[] Grobal 조류탐지 레이더 [] Web 풀스택 개발",
      "company": "에이치알포유(주)",
      "location": "경기",
      "deadline": "2026-05-17",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력5년 대졸(4년)",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=2605100000145&infoTypeCd=CIN&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 풀스택"
    },
    {
      "title": "2026 브랜드 퍼포먼스 마케터 경력직 채용 (인하우스)",
      "company": "(주)브렝땅",
      "location": "서울 강동구",
      "deadline": "2026-06-09",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력무관 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=53842399&infoTypeCd=CSI&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 퍼포먼스 마케터"
    },
    {
      "title": "호텔 무인 관제 매니저 &SW 개발자(백엔드/프론트)",
      "company": "주식회사슬기로운낭만지기",
      "location": "인천 연수구",
      "deadline": "2026-06-09",
      "type": "",
      "salary": "월급 320 만원 ~ 320 만원",
      "description": "경력무관 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=53842492&infoTypeCd=CSI&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "AI 음악 스타트업 Muzig 풀스택 개발자 크루 채용",
      "company": "아티움그룹(주)",
      "location": "서울 마포구",
      "deadline": "2026-07-08",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력무관 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=53840155&infoTypeCd=CSI&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "[콘텐츠 제작 담당자] 유튜브·숏폼 기획/촬영/편집 채용",
      "company": "(주)셀렉터",
      "location": "부산 동래구  등",
      "deadline": "2026-06-08",
      "type": "",
      "salary": "회사내규에 따름",
      "description": "경력무관 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=53840417&infoTypeCd=CSI&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "키워드: 숏폼"
    },
    {
      "title": "서비스(바리스타/카페매니저) 모집",
      "company": "투썸플레이스울산정자점",
      "location": "울산 북구",
      "deadline": "2026-06-08",
      "type": "",
      "salary": "월급 236 만원 ~ 236 만원",
      "description": "경력무관 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=53841781&infoTypeCd=CSI&infoTypeGroup=tb_workinfogubun",
      "source": "고용24",
      "_exclude_reason": "업체명: 투썸플레이스"
    },
    {
      "title": "자동화 장비 설계, S/W, 제조직 신입 공채",
      "company": "(주)제이렘",
      "location": "경기도 수원시 권선구",
      "deadline": "2026-07-07",
      "type": "",
      "salary": "연봉 3,071 만원 ~ 3,394 만원",
      "description": "신입 고졸\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t ~ 대졸(4년)",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=K180012605080059&infoTypeCd=VALIDATION&infoTypeGroup=tb_workinfoworknet",
      "source": "고용24",
      "_exclude_reason": "키워드: 신입 공채"
    },
    {
      "title": "자동화장치 및 로봇 개발자",
      "company": "주식회사선반도체",
      "location": "충청북도 청주시 흥덕구",
      "deadline": "2026-07-07",
      "type": "",
      "salary": "연봉 3,000 만원 ~ 5,000 만원",
      "description": "경력무관 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=K171112605080049&infoTypeCd=VALIDATION&infoTypeGroup=tb_workinfoworknet",
      "source": "고용24",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "연구소 하드웨어 개발자 모집",
      "company": "（주）이레씨즈",
      "location": "경기도 안양시 동안구",
      "deadline": "2026-07-07",
      "type": "",
      "salary": "연봉 4,000 만원 이상",
      "description": "경력3년 학력무관",
      "apply_link": "https://www.work24.go.kr/wk/a/b/1500/empDetailAuthView.do?wantedAuthNo=K180412605080024&infoTypeCd=VALIDATION&infoTypeGroup=tb_workinfoworknet",
      "source": "고용24",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "올리브영 롯데몰김포공항점  평일오픈(09:00-15:30) CREW 구인",
      "company": "씨제이올리브영 주식회사",
      "location": "인천 서구",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116435633",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "올리브영 노량진역점 평일(목금토일) 마감 CREW 구인",
      "company": "씨제이올리브영 주식회사",
      "location": "서울 동작구",
      "deadline": "2026-05-24",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116479010",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "[직영] 투썸플레이스 상암KBS미디어센터점 마감스탭 채용",
      "company": "투썸플레이스 상암KBS미디어센터점",
      "location": "서울 마포구 상암동",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,400원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116317231",
      "source": "알바몬",
      "_exclude_reason": "업체명: 투썸플레이스"
    },
    {
      "title": "[신규점] CJ올리브영 세로수길점 주말 마감 CREW 구인",
      "company": "씨제이올리브영 주식회사",
      "location": "서울 은평구 불광동",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116309179",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "CJ 올리브영 김포한강로점 주말마감 CREW 구인(14-22)",
      "company": "씨제이올리브영 주식회사",
      "location": "경기 김포시 구래동",
      "deadline": "2026-05-29",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116480710",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "[코엑스/삼성역]올리브영 파르나스삼성 타운 주말 오픈 CREW 구인",
      "company": "씨제이올리브영 주식회사",
      "location": "서울 동대문구 장안동",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116417357",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "올리브영 센트럴 강남 타운 토일 마감 CREW 구인",
      "company": "CJ올리브영 센트럴 강남 타운",
      "location": "서울 서초구",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116303781",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "올리브영 학동역점 월,화,수,목요일오픈 CREW 구인(시간,요일협의가능)",
      "company": "씨제이올리브영 주식회사",
      "location": "서울 강남구 논현동",
      "deadline": "2026-05-16",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116319592",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "[직영점] 투썸플레이스 경복아파트사거리점 마감 스탭 채용 선정릉역5분",
      "company": "투썸플레이스 경복아파트사거리점",
      "location": "서울 강남구 신사동",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,400원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116303778",
      "source": "알바몬",
      "_exclude_reason": "업체명: 투썸플레이스"
    },
    {
      "title": "[급구] 올리브영 압구정로데오점 주말 마감 CREW 구인",
      "company": "씨제이올리브영 주식회사",
      "location": "서울 관악구 봉천동",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116254736",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "[직영점/마감 홀청소X] 투썸플레이스 양재매헌역점 스탭(STAFF) 채용",
      "company": "투썸플레이스 양재매헌역점",
      "location": "서울 강남구",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,400원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116381576",
      "source": "알바몬",
      "_exclude_reason": "업체명: 투썸플레이스"
    },
    {
      "title": "CJ올리브영 여의도IFC점 주말마감 CREW 구인(시간/요일 협의 가능)",
      "company": "씨제이올리브영 주식회사",
      "location": "서울 양천구 목4동",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116489853",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "올리브영 남부터미널점 (금,토,일 마감) CREW 구인",
      "company": "씨제이올리브영 주식회사",
      "location": "서울 서초구",
      "deadline": "2026-05-17",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116388177",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "올리브영 운서역점 평일 마감 CREW 구인",
      "company": "씨제이올리브영 주식회사",
      "location": "인천 부평구",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116334644",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "[직영점]투썸플레이스 행담도점 월급제 사원(캡틴) 채용 모집",
      "company": "투썸플레이스 행담도휴게소(하)점",
      "location": "충남 전체",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "월급 2,500,000원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116388172",
      "source": "알바몬",
      "_exclude_reason": "업체명: 투썸플레이스"
    },
    {
      "title": "노브랜드버거 매니저 알바채용",
      "company": "노브랜드버거 대전관평점",
      "location": "대전 유성구 관평동",
      "deadline": "2026-05-16",
      "type": "시간제",
      "salary": "시급 10,320원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116422560",
      "source": "알바몬",
      "_exclude_reason": "업체명: 노브랜드버거"
    },
    {
      "title": "노브랜드버거 서초자이점 파트타이머 10:00~14:00 모집!",
      "company": "노브랜드버거 서초자이점",
      "location": "서울 강남구",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 12,384원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116264866",
      "source": "알바몬",
      "_exclude_reason": "업체명: 노브랜드버거"
    },
    {
      "title": "컴포즈커피 채용공고",
      "company": "컴포즈커피 하계을지병원점",
      "location": "서울 노원구 하계동",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,320원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116492336",
      "source": "알바몬",
      "_exclude_reason": "업체명: 컴포즈"
    },
    {
      "title": "컴포즈커피 검단금호점 주중 오픈&미들,  주말 오픈 파트타이머 구합니다",
      "company": "컴포즈커피 검단금호점",
      "location": "인천 서구",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,500원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116484740",
      "source": "알바몬",
      "_exclude_reason": "업체명: 컴포즈"
    },
    {
      "title": "CJ올리브영 운서점 평일 마감 CREW 모집합니다 (협의가능)",
      "company": "씨제이올리브영 주식회사",
      "location": "인천 전체",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116383163",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "올리브영 공덕역점 목토일 오픈 CREW 구인",
      "company": "씨제이올리브영 공덕역점",
      "location": "서울 전체",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116345136",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "올리브영 구월 타운 평일 마감 CREW 구인",
      "company": "씨제이올리브영 주식회사",
      "location": "인천 전체",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116487393",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "[신규점] CJ올리브영 세로수길점 주말 오픈 CREW 구인",
      "company": "씨제이올리브영 주식회사",
      "location": "경기 고양시 덕양구 지축동",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116309159",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "(급구)CJ 올리브영 선릉점 화 마감/ 목,금 미들 CREW구인",
      "company": "씨제이올리브영 주식회사",
      "location": "서울 강남구",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 10,600원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116317218",
      "source": "알바몬",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "컴포즈커피 마포신수점 평일 주5일 마감알바 모집 / 시급 13,000원",
      "company": "컴포즈커피 마포신수점",
      "location": "서울 마포구 신수동",
      "deadline": "상시모집",
      "type": "시간제",
      "salary": "시급 13,000원",
      "description": "",
      "apply_link": "https://www.albamon.com/jobs/detail/116303746",
      "source": "알바몬",
      "_exclude_reason": "업체명: 컴포즈"
    },
    {
      "title": "[금천구 가산동]맥도날드 가산디지털점에서 함께 근무하실 분을 구합니다",
      "company": "맥도날드 가산 디지털점",
      "location": "서울 금천구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144062665&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "[전포동]맥도날드 서면3호점에서 크루 모집합니다.",
      "company": "맥도날드 서면 III점",
      "location": "부산 부산진구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143794993&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "[급구]강남구청역 KFC 3/26 신규오픈멤버가 되어주실 분 구합니다",
      "company": "KFC 강남구청역",
      "location": "서울 강남구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144013741&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: kfc"
    },
    {
      "title": "M신촌역 세븐일레븐에서 같이 근무 할 아르바이트 모집중",
      "company": "세븐일레븐 M신촌역점",
      "location": "서울 마포구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144035658&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 세븐일레븐"
    },
    {
      "title": "[광주광역시] 맥도날드 상무대점에서 평일/주말 크루를 채용합니다.",
      "company": "맥도날드 상무대점",
      "location": "광주 서구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143801501&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "[스타벅스] 제주협재점 바리스타 모집",
      "company": "스타벅스 제주협재",
      "location": "제주 제주시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143848349&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "근로복지 최고, 강남메카~ 압구정역점 알바모집(리아 경력 최고대우)",
      "company": "롯데리아 압구정역",
      "location": "서울 전체",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144010208&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "스타벅스 세종아름점 바리스타 모집",
      "company": "스타벅스 세종아름",
      "location": "세종 전체",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143921041&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "롯데리아 대소점 부점장(경력자) 모집/원룸제공가능",
      "company": "롯데리아 대소",
      "location": "충북 전체",
      "deadline": "",
      "type": "시간제",
      "salary": "월급 2800000",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143967574&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "올리브영 경주황남점 평일 물류 Crew 구인(월수금)",
      "company": "씨제이올리브영 주식회사",
      "location": "경북 경주시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10600",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144008544&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "[범천동]맥도날드 서면3호점에서 크루 모집합니다.",
      "company": "맥도날드 서면 III점",
      "location": "부산 부산진구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143794962&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "스타벅스 합정메세나몰점 바리스타 모집",
      "company": "스타벅스 합정메세나몰",
      "location": "서울 마포구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143932664&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "투썸플레이스 개포언주로점 주말 알바 모집",
      "company": "투썸플레이스 개포언주로점",
      "location": "서울 강남구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10550",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143975068&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 투썸플레이스"
    },
    {
      "title": "광주상무DI점 평일마감/금토일 파트타임 구인",
      "company": "KFC KFC광주상무DI",
      "location": "광주 전체",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144059485&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: kfc"
    },
    {
      "title": "CJ 올리브영 서산테크노밸리점 주말 마감 Crew 구인 (시간 협의 가능)",
      "company": "씨제이올리브영 주식회사",
      "location": "충남 서산시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10600",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143944626&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 올리브영"
    },
    {
      "title": "맥도날드 목원대점 전 시간대 크루 모집 (주말 1일 이상 가능자 우대)",
      "company": "맥도날드 목원대",
      "location": "대전 전체",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143965157&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "스타벅스 고척아이파크점 바리스타 모집",
      "company": "스타벅스 고척아이파크",
      "location": "경기 광명시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144041320&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "맥도날드 연신내점 아르바이트 모집 [평일 전시간대 환영] 크루 모집",
      "company": "맥도날드 연신내점",
      "location": "서울 은평구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143913603&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "[일산호수공원점] / 전시간대 모집 / 호수공원에서 일할 크루 모집",
      "company": "버거킹 일산호수공원",
      "location": "경기 고양시 일산동구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144062654&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 버거킹"
    },
    {
      "title": "투썸플레이스 금천광장점 일월화 마감(19-24)",
      "company": "투썸플레이스 금천점",
      "location": "충북 청주시 상당구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143838685&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 투썸플레이스"
    },
    {
      "title": "엔제리너스 석촌호수D/I점에서 주말마감 근무 하실 분 모십니다",
      "company": "엔제리너스 석촌호수D/I점",
      "location": "서울 송파구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144067272&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 엔제리너스"
    },
    {
      "title": "할리스커피 간석오거리점 주3,4일 마감PT구합니다.",
      "company": "할리스커피 간석오거리점",
      "location": "인천 남동구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143981568&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 할리스"
    },
    {
      "title": "[제주시] 맥도날드 제주일도DT점에서 함께 일할 크루를 모집합니다.",
      "company": "맥도날드 제주 일도 DT점",
      "location": "제주 제주시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143838683&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "[스타벅스 아산방축DT] 스타벅스 아산방축DT점에서 바리스타를 모집합니다.",
      "company": "스타벅스 아산방축DT",
      "location": "충남 아산시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144070405&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "KFC시청역 평일주말(심야채용 새벽1시~아침9시)야간수당1.5배주휴택시비지원",
      "company": "KFC 대전타임월드",
      "location": "대전 전체",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144039129&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: kfc"
    },
    {
      "title": "맥도날드 양산DT점에서 함께 근무 할 크루 구합니다.주말가능자우대/협의가능",
      "company": "맥도날드 양산 DT점",
      "location": "경남 양산시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143932631&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "스타벅스 울산정자비치DT점 바리스타 모집",
      "company": "스타벅스 울산정자비치DT",
      "location": "울산 북구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143871943&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "[서귀포 신시가지]맥도날드 월드컵DT점에서 크루를 모집합니다.",
      "company": "맥도날드 제주월드컵스타디움DT",
      "location": "제주 서귀포시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143845234&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "[서울 도봉구]맥도날드 방학역DT점에서 크루를 모집합니다 .",
      "company": "맥도날드 방학역DT",
      "location": "서울 도봉구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144010182&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "맥도날드 양산DT점에서 함께 근무 할 크루 구합니다. 금토 23-07",
      "company": "맥도날드 양산 DT점",
      "location": "경남 양산시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143932612&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "롯데리아 점촌점 직원 모집",
      "company": "롯데리아 점촌점",
      "location": "경북 문경시",
      "deadline": "",
      "type": "시간제",
      "salary": "월급 1650000",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143951967&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "[고양삼송DT점 크루 모집] 평일, 주말 오전 오후 야간 시간대",
      "company": "맥도날드 고양삼송DT점",
      "location": "경기 고양시 덕양구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144029969&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "[07-15,15-23,23-07] 의왕오전DT점 크루님 모집합니다",
      "company": "맥도날드 의왕 오전 DT점",
      "location": "경기 안양시 동안구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143993080&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "맥도날드 진접DT점 (오전,오후,야간) 주말 포함 크루 모집합니다.",
      "company": "맥도날드 진접 DT점",
      "location": "경기 남양주시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143823862&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "KFC시청역평일주말오전채용,마감심야채용야간수당1.5배주휴수당택시비(4대보험)",
      "company": "KFC 대전시청역",
      "location": "대전 서구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144039054&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: kfc"
    },
    {
      "title": "스타벅스 인천공항T1에어4F점 바리스타 모집 (교통비/주차비 지원)",
      "company": "스타벅스 인천공항T1에어4F",
      "location": "인천 중구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144035577&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "롯데리아 부점장하실분",
      "company": "롯데리아 평택안중",
      "location": "경기 평택시",
      "deadline": "",
      "type": "시간제",
      "salary": "월급 2460000",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144035573&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "투썸플레이스 전주에코호수DT점에서 평일마감스텝 모집합니다.",
      "company": "투썸플레이스 에코호수DT",
      "location": "전북 전주시 덕진구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143974987&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 투썸플레이스"
    },
    {
      "title": "투썸플레이스 음성공장 디저트 생산 시급제 스탭 모집 (정규직 전환가능)",
      "company": "투썸플레이스(주)",
      "location": "충북 음성군",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10500",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143974985&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 투썸플레이스"
    },
    {
      "title": "롯데리아 목동사거리점에서아르바이트 하실분 모십니다.(평일.주말,투잡가능)",
      "company": "롯데리아 목동사거리",
      "location": "서울 양천구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143974965&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "출근하면 생각보다 참 좋다. 안암오거리점 버거킹 크루 모집",
      "company": "버거킹 안암오거리점",
      "location": "서울 성북구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143833883&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 버거킹"
    },
    {
      "title": "롯데리아 예천점에서 함께 하실 직원 모집합니다~ 장기근무자 환영합니다~",
      "company": "롯데리아 예천점",
      "location": "경북 예천군",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143833871&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "원하는시간요일 조정가능 맥도날드 송파잠실DT점에서 크루를 모집합니다",
      "company": "맥도날드 송파 잠실 DT점",
      "location": "서울 송파구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143794856&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "[가야동]맥도날드 서면3호점에서 크루 모집합니다.",
      "company": "맥도날드 서면 III점",
      "location": "부산 부산진구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143794854&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "스타벅스 건대스타시티점에서 함께 근무할 주말 바리스타를 모집합니다",
      "company": "스타벅스 건대스타시티",
      "location": "서울 광진구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144072963&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "삼성동 버거킹 - 주말 / 평일 모든 시간대",
      "company": "버거킹 삼성중앙역점",
      "location": "서울 강남구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144070393&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 버거킹"
    },
    {
      "title": "직영롯데리아 울산터미널점에서 아르바이트 모집해요",
      "company": "롯데리아 울산터미날점",
      "location": "울산 남구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144063933&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "[스타벅스 대전신흥역DT] 스타벅스 대전 신흥역DT점 바리스타 모집",
      "company": "스타벅스 대전신흥역DT",
      "location": "대전 동구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144057899&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "[교통비 일 15,000원] 스타벅스 인스파이어리조트점 25h 바리스타 모집",
      "company": "스타벅스 인스파이어리조트",
      "location": "인천 중구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143987924&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "맥도날드 충남보령DT점과 함께할 크루 모집합니다",
      "company": "맥도날드 충남 보령 DT점",
      "location": "충남 보령시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143951962&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "롯데리아 점촌점 아르바이트 모집(주부, 휴학생,취준생 환영,6개월이상 필수)",
      "company": "롯데리아 점촌점",
      "location": "경북 문경시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10500",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143951961&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "롯데리아 점촌점 평일, 주말 아르바이트 모집",
      "company": "롯데리아 점촌점",
      "location": "경북 문경시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10500",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143951960&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "[교통비지급] 양주휴게소 맥도날드 직원 모집합니다. [고양동, 지축역 인근]",
      "company": "맥도날드 양주 휴게소 DT점",
      "location": "경기 고양시 덕양구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143950263&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "[버거킹 안양중앙시장점] 신규오픈 전시간대 근무자 구해용",
      "company": "버거킹 안양중앙시장점",
      "location": "경기 안양시 동안구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143943531&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 버거킹"
    },
    {
      "title": "(급구)롯데리아 숙대입구역점 심야 아르바이트생을 모집합니다. 경력자 우대",
      "company": "롯데리아 숙대입구역",
      "location": "서울 전체",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143943524&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "롯데리아 부산진역점 오전 또는 저녁시간 알바모집합니다.",
      "company": "롯데리아 부산진역점",
      "location": "부산 전체",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143920998&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "커피빈 마포경찰공제회점 5H 정규직 수퍼바이저 구인",
      "company": "(주)커피빈코리아",
      "location": "서울 마포구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143911335&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 커피빈"
    },
    {
      "title": "[롯데리아 강릉교동점] 대체 얼마나 채용할지 감도 안옴",
      "company": "롯데리아 강릉교동점",
      "location": "강원 강릉시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143911328&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "버거킹 아차산역점에서 같이 근무하실 분 모집합니다.",
      "company": "버거킹 아차산역점",
      "location": "서울 광진구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143903290&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 버거킹"
    },
    {
      "title": "스타벅스 만성DT점 바리스타 모집",
      "company": "스타벅스 전주만성DT",
      "location": "전북 전체",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143902230&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "스타벅스 용산리첸시아점 바리스타 모집",
      "company": "스타벅스 용산리첸시아",
      "location": "서울 용산구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143898577&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "롯데리아 안산그랑시티자이점 MATE[경력자환영] 모집",
      "company": "롯데리아 안산그랑시티자이",
      "location": "경기 안산시 상록구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143898574&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "롯데리아 신길점 아르바이트 모집합니다",
      "company": "롯데리아 신길점",
      "location": "서울 전체",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143871896&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "스타벅스동광주DT 점에서 함께 근무하실 파트너를 모집합니다",
      "company": "스타벅스 동광주DT",
      "location": "광주 북구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143858602&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "[서울시/강남구/급구]삼성역점 맥도날드 크루 모집(평일 오전타임)",
      "company": "맥도날드 삼성역점",
      "location": "서울 강남구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143848275&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "부점장(롯데리아교육이수자) 모집합니다 (기본급 300만원~)",
      "company": "롯데리아 수원권선",
      "location": "경기 수원시 권선구",
      "deadline": "",
      "type": "시간제",
      "salary": "월급 3000000",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143848273&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "수원권선점 아르바이트 구인",
      "company": "롯데리아 수원권선",
      "location": "경기 수원시 권선구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143848272&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "맥도날드 대전터미널점 크루 모집",
      "company": "맥도날드 대전터미널",
      "location": "대전 동구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143812788&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "롯데리아 송악점 평일 마감(20시~22시) 청소 직원 모집(이주단지)",
      "company": "롯데리아 송악점",
      "location": "충남 당진시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143812784&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "[강남 삼성역 코엑스] 맥도날드 코엑스점 모든 요일 크루 모집합니다",
      "company": "맥도날드 코엑스점",
      "location": "서울 강남구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=143801419&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "스타벅스 분당구청점에서 함께 일할 바리스타를 찾습니다.",
      "company": "스타벅스 분당구청",
      "location": "경기 성남시 분당구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144079438&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "투썸플레이스 마포망원점-목금미들 스텝",
      "company": "투썸플레이스 마포망원점",
      "location": "서울 마포구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10500",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144075349&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 투썸플레이스"
    },
    {
      "title": "롯데리아 강남역SELECT점 평일 오전 오후, 주말 아르바이트",
      "company": "롯데리아 리아 강남역SELECT",
      "location": "서울 강남구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144060523&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "원주기업도시버거킹 주말 및 평일 아르바이트 모집 (고령자, 2잡 모두 가능",
      "company": "버거킹 원주기업도시점(S)",
      "location": "강원 원주시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144054835&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 버거킹"
    },
    {
      "title": "원주기업도시점 버거킹 매니저 모집 (정규직)",
      "company": "버거킹 원주기업도시점(S)",
      "location": "강원 원주시",
      "deadline": "",
      "type": "시간제",
      "salary": "월급 2360000",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144054834&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 버거킹"
    },
    {
      "title": "커피빈 광화문역1번출구점 4H 슈퍼바이저 채용",
      "company": "커피빈 광화문역1번출구점",
      "location": "서울 전체",
      "deadline": "",
      "type": "시간제",
      "salary": "월급 1123600",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144047049&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 커피빈"
    },
    {
      "title": "[스타벅스] 문정법조타운 한양타워점에서 함께할 바리스타 파트너를 모집합니다.",
      "company": "스타벅스 문정법조타운 한양타워",
      "location": "서울 전체",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 11250",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144047048&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 스타벅스"
    },
    {
      "title": "맥도날드 영등포점 크루 모집",
      "company": "맥도날드 영등포점",
      "location": "서울 영등포구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144047045&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "[경북 영천시] 맥도날드 경북영천DT점에서 함께 근무할 크루를 모집합니다",
      "company": "맥도날드 경북영천 DT점",
      "location": "경북 영천시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144015797&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "주말구인합니다",
      "company": "롯데리아 창원감계점",
      "location": "경남 창원시 의창구",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144015794&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 롯데리아"
    },
    {
      "title": "[강원도원주시] 맥도날드 원주단구DT점에서 함께할 크루를 모집합니다.",
      "company": "맥도날드 원주단구DT",
      "location": "강원 원주시",
      "deadline": "",
      "type": "시간제",
      "salary": "시급 10320",
      "description": "",
      "apply_link": "https://www.alba.co.kr/job/Detail?adid=144015782&listmenucd=SENIOR",
      "source": "알바천국",
      "_exclude_reason": "업체명: 맥도날드"
    },
    {
      "title": "제품 시각/그래픽 디자이너 채용공고",
      "company": "주식회사 멜로우스페이스",
      "location": "하남시",
      "deadline": "2026-04-30",
      "type": "정규직",
      "salary": "연봉 2600만원 ~ 3800만원",
      "description": "",
      "apply_link": "http://www.work.go.kr/empInfo/empInfoSrch/detail/empDetailAuthView.do?wantedAuthNo=K180342604010010",
      "source": "잡아바",
      "_exclude_reason": "키워드: 그래픽 디자이너"
    },
    {
      "title": "원평산업(주) 생산직 모집 /2교대/병역특례 지원...",
      "company": "원평산업(주)",
      "location": "안산시",
      "deadline": "2026-05-02",
      "type": "정규직",
      "salary": "시급 10520원 ~ 10520원",
      "description": "",
      "apply_link": "http://www.work.go.kr/empInfo/empInfoSrch/detail/empDetailAuthView.do?wantedAuthNo=KJKP002603030019",
      "source": "잡아바",
      "_exclude_reason": "키워드: 병역특례"
    },
    {
      "title": "2026년 Web(java) 개발자 채용",
      "company": "(주)거룡아이티",
      "location": "고양시",
      "deadline": "2026-05-03",
      "type": "계약직",
      "salary": "연봉 3000만원 ~ 5000만원",
      "description": "",
      "apply_link": "http://www.work.go.kr/empInfo/empInfoSrch/detail/empDetailAuthView.do?wantedAuthNo=K180212604170027",
      "source": "잡아바",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "자동차 안전밸트 관련 생산직 모집/2교대/병역특례...",
      "company": "풍국기업(주)",
      "location": "안산시",
      "deadline": "2026-05-02",
      "type": "정규직",
      "salary": "시급 10520원 ~ 10520원",
      "description": "",
      "apply_link": "http://www.work.go.kr/empInfo/empInfoSrch/detail/empDetailAuthView.do?wantedAuthNo=KJKP002603030021",
      "source": "잡아바",
      "_exclude_reason": "키워드: 병역특례"
    },
    {
      "title": "2026년 상반기 HRD/조직문화 채용연계형 인턴 모집",
      "company": "SK가스(주)",
      "location": "성남시",
      "deadline": "2026-05-10",
      "type": "",
      "salary": "",
      "description": "",
      "apply_link": "https://www.jobkorea.co.kr/Recruit/GI_Read/49074786?Oem_Code=C900&api=232",
      "source": "잡아바",
      "_exclude_reason": "키워드: 채용연계형 인턴"
    },
    {
      "title": "소스류 및 식품 개발자 초빙",
      "company": "(주)우복당식품",
      "location": "안양시",
      "deadline": "2026-05-24",
      "type": "정규직",
      "salary": "연봉 4000만원 ~ 5000만원",
      "description": "",
      "apply_link": "http://www.work.go.kr/empInfo/empInfoSrch/detail/empDetailAuthView.do?wantedAuthNo=K180032603250034",
      "source": "잡아바",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "AI 개발자 모집 프리랜서",
      "company": "(주)누리인포스",
      "location": "성남시,수원시",
      "deadline": "2026-05-28",
      "type": "",
      "salary": "",
      "description": "",
      "apply_link": "https://www.jobkorea.co.kr/Recruit/GI_Read/49074628?Oem_Code=C900&api=232",
      "source": "잡아바",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "[픽플러스] 프론트엔드/백엔드 개발자 경력자 채용",
      "company": "(주)픽플러스",
      "location": "고양시",
      "deadline": "2026-05-28",
      "type": "계약직",
      "salary": "",
      "description": "",
      "apply_link": "https://www.jobkorea.co.kr/Recruit/GI_Read/49075303?Oem_Code=C900&api=232",
      "source": "잡아바",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "[판교/글로벌기업] 백엔드 개발자 (Java/팀원)",
      "company": "(주)이파피루스",
      "location": "성남시",
      "deadline": "2026-05-28",
      "type": "",
      "salary": "",
      "description": "",
      "apply_link": "https://www.jobkorea.co.kr/Recruit/GI_Read/49075656?Oem_Code=C900&api=232",
      "source": "잡아바",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "2026 로밍도깨비 퍼포먼스 마케터 담당자 모집",
      "company": "유엔젤(주)",
      "location": "성남시",
      "deadline": "2026-05-29",
      "type": "",
      "salary": "",
      "description": "",
      "apply_link": "https://www.jobkorea.co.kr/Recruit/GI_Read/49053507?Oem_Code=C900&api=232",
      "source": "잡아바",
      "_exclude_reason": "키워드: 퍼포먼스 마케터"
    },
    {
      "title": "[일반] 그리다 랩_게임 기획 및 게임 스크립트 작성",
      "company": "그리다 랩",
      "location": "부천시",
      "deadline": "2026-08-31",
      "type": "",
      "salary": "3000 ~ 4000 만원",
      "description": "",
      "apply_link": "https://job.gg.go.kr/empmn/jobEntDtl.do?seq=14554",
      "source": "잡아바",
      "_exclude_reason": "키워드: 게임 기획"
    },
    {
      "title": "[일반] 참참바이오 주식회사_풀스텍, 백엔드 개발자",
      "company": "참참바이오 주식회사",
      "location": "화성시",
      "deadline": "2026-08-31",
      "type": "",
      "salary": "3000 ~ 4000 만원",
      "description": "",
      "apply_link": "https://job.gg.go.kr/empmn/jobEntDtl.do?seq=14571",
      "source": "잡아바",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "전기자동차충전기업체 S/W 개발자 모집 2026....",
      "company": "(주)파워큐브코리아",
      "location": "의왕시",
      "deadline": "2026-06-09",
      "type": "계약직",
      "salary": "연봉 3000만원 ~ 6000만원",
      "description": "",
      "apply_link": "http://www.work.go.kr/empInfo/empInfoSrch/detail/empDetailAuthView.do?wantedAuthNo=KJKY002604100004",
      "source": "잡아바",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "[모집] 병역특례 -기계,전기,전자,용접",
      "company": "(주)일신바이오베이스",
      "location": "동두천시",
      "deadline": "2026-06-20",
      "type": "계약직",
      "salary": "연봉 2588만원 ~ 3000만원",
      "description": "",
      "apply_link": "http://www.work.go.kr/empInfo/empInfoSrch/detail/empDetailAuthView.do?wantedAuthNo=K180142604210012",
      "source": "잡아바",
      "_exclude_reason": "키워드: 병역특례"
    },
    {
      "title": "[일반]주식회사 그랜드소프트_풀스택 개발자",
      "company": "주식회사 그랜드소프트",
      "location": "성남시",
      "deadline": "2026-08-31",
      "type": "",
      "salary": "3000 ~ 4000 만원",
      "description": "",
      "apply_link": "https://job.gg.go.kr/empmn/jobEntDtl.do?seq=14609",
      "source": "잡아바",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "카메라 모듈 검사 Firmware 개발자 모집",
      "company": "(주)다람기술",
      "location": "평택시",
      "deadline": "2026-06-12",
      "type": "정규직",
      "salary": "월급 220만원 ~ 240만원",
      "description": "",
      "apply_link": "http://www.work.go.kr/empInfo/empInfoSrch/detail/empDetailAuthView.do?wantedAuthNo=K180612604140003",
      "source": "잡아바",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "Java MES 개발자 - 스마트팩토리 경력자 모집 (Python, AI 경력우대)",
      "company": "건솔루션(주)",
      "location": "경기전체,안양시,서울특별시",
      "deadline": "2026-06-30",
      "type": "",
      "salary": "",
      "description": "",
      "apply_link": "https://www.jobkorea.co.kr/Recruit/GI_Read/49074461?Oem_Code=C900&api=232",
      "source": "잡아바",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "[일반] 주식회사 그랜드소프트_ 개발자",
      "company": "주식회사 그랜드소프트",
      "location": "성남시",
      "deadline": "2026-08-31",
      "type": "",
      "salary": "3000 ~ 4000 만원",
      "description": "",
      "apply_link": "https://job.gg.go.kr/empmn/jobEntDtl.do?seq=14611",
      "source": "잡아바",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "[북부특화] 주식회사 케어클_퍼포먼스 마케터",
      "company": "주식회사 케어클",
      "location": "고양시",
      "deadline": "2026-08-31",
      "type": "",
      "salary": "2500 ~ 3000 만원",
      "description": "",
      "apply_link": "https://job.gg.go.kr/empmn/jobEntDtl.do?seq=14525",
      "source": "잡아바",
      "_exclude_reason": "키워드: 퍼포먼스 마케터"
    },
    {
      "title": "[일반] (주)우보재난시스템_기술연구소 백엔드 개발",
      "company": "(주)우보재난시스템",
      "location": "성남시",
      "deadline": "2026-08-31",
      "type": "",
      "salary": "3000 ~ 4000 만원",
      "description": "",
      "apply_link": "https://job.gg.go.kr/empmn/jobEntDtl.do?seq=14542",
      "source": "잡아바",
      "_exclude_reason": "키워드: 백엔드"
    },
    {
      "title": "[일반] (주)우보재난시스템_기술연구소 H/W 및 F/W 개발자",
      "company": "(주)우보재난시스템",
      "location": "성남시",
      "deadline": "2026-08-31",
      "type": "",
      "salary": "3000 ~ 4000 만원",
      "description": "",
      "apply_link": "https://job.gg.go.kr/empmn/jobEntDtl.do?seq=14544",
      "source": "잡아바",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "[일반] (주)우보재난시스템_기술연구소 WEB PHP 개발자",
      "company": "(주)우보재난시스템",
      "location": "성남시",
      "deadline": "2026-08-31",
      "type": "",
      "salary": "3000 ~ 4000 만원",
      "description": "",
      "apply_link": "https://job.gg.go.kr/empmn/jobEntDtl.do?seq=14547",
      "source": "잡아바",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "[일반] 주식회사 아이디벨_UI/UX 디자이너",
      "company": "(주)아이디벨",
      "location": "하남시",
      "deadline": "2026-08-31",
      "type": "",
      "salary": "3000 ~ 4000 만원",
      "description": "",
      "apply_link": "https://job.gg.go.kr/empmn/jobEntDtl.do?seq=14657",
      "source": "잡아바",
      "_exclude_reason": "키워드: ui/ux 디자이너"
    },
    {
      "title": "[일반]시큐와우 주식회사_ 연구개발자",
      "company": "시큐와우㈜",
      "location": "안양시",
      "deadline": "2026-08-31",
      "type": "",
      "salary": "3000 ~ 4000 만원",
      "description": "",
      "apply_link": "https://job.gg.go.kr/empmn/jobEntDtl.do?seq=14675",
      "source": "잡아바",
      "_exclude_reason": "키워드: 개발자"
    },
    {
      "title": "[일반] (주)레드마우스_프론트엔드개발",
      "company": "(주)레드마우스",
      "location": "화성시",
      "deadline": "2026-08-31",
      "type": "",
      "salary": "3000 ~ 4000 만원",
      "description": "",
      "apply_link": "https://job.gg.go.kr/empmn/jobEntDtl.do?seq=14680",
      "source": "잡아바",
      "_exclude_reason": "키워드: 프론트엔드"
    },
    {
      "title": "[일반] (주)레드마우스_백엔드 개발",
      "company": "(주)레드마우스",
      "location": "화성시",
      "deadline": "2026-08-31",
      "type": "",
      "salary": "3000 ~ 4000 만원",
      "description": "",
      "apply_link": "https://job.gg.go.kr/empmn/jobEntDtl.do?seq=14681",
      "source": "잡아바",
      "_exclude_reason": "키워드: 백엔드"
    }
  ],
  "filter_config": {
    "companies": [
      "24시스포츠",
      "cgv",
      "cu편의점",
      "gs25",
      "kfc",
      "게임빌",
      "공차",
      "넥슨",
      "넷마블",
      "노브랜드버거",
      "더벤티",
      "더피트",
      "던킨",
      "롯데리아",
      "롯데시네마",
      "맘스터치",
      "맥도날드",
      "메가박스",
      "메가커피",
      "무신사",
      "배달의민족",
      "배스킨라빈스",
      "버거킹",
      "브랜디",
      "블루보틀",
      "빽다방",
      "서브웨이",
      "세븐일레븐",
      "쉐이크쉑",
      "스마일게이트",
      "스타벅스",
      "스파오",
      "스포애니",
      "씨네큐",
      "애니타임피트니스",
      "에이블리",
      "엔씨소프트",
      "엔제리너스",
      "올리브영",
      "요기요",
      "위메이드",
      "이디야",
      "이마트24",
      "지그재그",
      "카카오게임즈",
      "카페베네",
      "커피빈",
      "컴투스",
      "컴포즈",
      "쿠팡이츠",
      "크래프톤",
      "크리스피크림",
      "탐앤탐스",
      "탑텐",
      "투썸플레이스",
      "파스쿠찌",
      "파이브가이즈",
      "파파이스",
      "펄어비스",
      "폴바셋",
      "할리스"
    ],
    "keywords": [
      "나이트클럽",
      "유흥주점",
      "단란주점",
      "룸살롱",
      "룸카페",
      "호스트바",
      "바텐더",
      "호프집",
      "맥주집",
      "포장마차",
      "포차",
      "이자카야",
      "pc방",
      "피씨방",
      "코인노래방",
      "10대",
      "20대 초반",
      "나이 제한",
      "개발자",
      "백엔드 개발자",
      "프론트엔드 개발자",
      "풀스택 개발자",
      "프론트엔드",
      "백엔드",
      "풀스택",
      "ios 개발자",
      "android 개발자",
      "앱 개발자",
      "웹 개발자",
      "devops 엔지니어",
      "devops",
      "sre 엔지니어",
      "ui/ux 디자이너",
      "ux 디자이너",
      "ui 디자이너",
      "데이터 사이언티스트",
      "머신러닝 엔지니어",
      "딥러닝 엔지니어",
      "ai 엔지니어",
      "소프트웨어 엔지니어",
      "클라우드 엔지니어",
      "qa 엔지니어",
      "테스트 엔지니어",
      "데이터 분석가",
      "데이터 엔지니어",
      "데이터 사이언스",
      "게임 개발",
      "모바일 개발",
      "앱 개발",
      "프로덕트 매니저",
      "프로덕트 디자이너",
      "게임 pd",
      "웹퍼블리셔",
      "서비스 기획자",
      "it 기획자",
      "node.js",
      "react",
      "vue.js",
      "spring",
      "flutter",
      "kotlin",
      "typescript",
      "python 개발",
      "java 개발",
      "javascript",
      "인공지능 개발",
      "llm",
      "mlops",
      "클라우드 아키텍트",
      "블록체인",
      "web3",
      "nft",
      "병역특례",
      "그래픽 디자이너",
      "브랜드 디자이너",
      "모션 그래픽",
      "모션 디자이너",
      "영상 편집",
      "영상 제작자",
      "영상 pd",
      "3d 디자이너",
      "3d 모델러",
      "3d 아티스트",
      "게임 아티스트",
      "콘셉트 아티스트",
      "캐릭터 디자이너",
      "배경 아티스트",
      "웹툰 작가",
      "만화 작가",
      "게임 기획",
      "게임 디자인",
      "e스포츠",
      "이스포츠",
      "프로게이머",
      "게임 스트리머",
      "유튜브 크리에이터",
      "유튜브 운영",
      "유튜브 편집",
      "틱톡 크리에이터",
      "틱톡 운영",
      "숏폼",
      "릴스 제작",
      "인플루언서",
      "인터넷 방송",
      "스트리머",
      "sns 마케터",
      "콘텐츠 크리에이터",
      "퍼포먼스 마케터",
      "퍼포먼스 마케팅",
      "그로스 마케터",
      "그로스 해킹",
      "seo 마케터",
      "앱 마케터",
      "배달 라이더",
      "배달기사",
      "오토바이 라이더",
      "퀵서비스 라이더",
      "오토바이 배달",
      "새벽 배송 기사",
      "쿠팡 로켓배송",
      "이삿짐",
      "헬스 트레이너",
      "퍼스널 트레이너",
      "pt 트레이너",
      "필라테스 강사",
      "요가 강사",
      "스피닝 강사",
      "인턴십",
      "채용연계형 인턴",
      "대졸 신입 공채",
      "신입 공채",
      "대학생 전용",
      "고등학생 가능"
    ]
  }
};
